// This file provides curated data for the MVP (Rajasthan)
// It mimics the database queries for the sandbox environment where MongoDB is not available.

export const MOCK_STATES = [
  {
    _id: 'RJ',
    code: 'RJ',
    name: 'Rajasthan',
    center: { lat: 26.5, lng: 73.8 },
    zoom: 7,
    description: 'The Land of Kings, featuring forts, deserts, and vibrant culture.',
    imageUrl: 'https://images.unsplash.com/photo-1477587458883-47145ed94245?auto=format&fit=crop&q=80',
  }
];

export const MOCK_CITIES = [
  {
    _id: 'jaipur',
    name: 'Jaipur',
    stateCode: 'RJ',
    coordinates: { lat: 26.9124, lng: 75.7873 },
    tier: 'tier1',
    description: 'The Pink City, famous for Hawa Mahal, Amer Fort, and City Palace.',
    idealDays: 2,
    imageUrl: 'https://images.unsplash.com/photo-1477587458883-47145ed94245?auto=format&fit=crop&q=80',
  },
  {
    _id: 'udaipur',
    name: 'Udaipur',
    stateCode: 'RJ',
    coordinates: { lat: 24.5854, lng: 73.7125 },
    tier: 'tier1',
    description: 'The City of Lakes, known for its romantic setting and palaces.',
    idealDays: 2,
    imageUrl: 'https://images.unsplash.com/photo-1615836245337-f5b9b2303f10?auto=format&fit=crop&q=80',
  },
  {
    _id: 'jodhpur',
    name: 'Jodhpur',
    stateCode: 'RJ',
    coordinates: { lat: 26.2389, lng: 73.0243 },
    tier: 'tier2',
    description: 'The Blue City, dominated by the massive Mehrangarh Fort.',
    idealDays: 2,
    imageUrl: 'https://images.unsplash.com/photo-1590449911964-b04b6b64731c?auto=format&fit=crop&q=80',
  },
  {
    _id: 'jaisalmer',
    name: 'Jaisalmer',
    stateCode: 'RJ',
    coordinates: { lat: 26.9157, lng: 70.9083 },
    tier: 'tier2',
    description: 'The Golden City, located in the heart of the Thar Desert.',
    idealDays: 2,
    imageUrl: 'https://images.unsplash.com/photo-1516483638261-f4dbaf036963?auto=format&fit=crop&q=80',
  }
];

export const MOCK_PLACES = [
  // JAIPUR
  {
    _id: 'amber_fort',
    name: 'Amber Fort',
    cityName: 'Jaipur',
    type: 'Fort',
    coordinates: { lat: 26.9855, lng: 75.8513 },
    timeRequired: 3,
    openingTime: '08:00',
    closingTime: '17:30',
    bestTimeOfDay: 'morning',
    rating: 4.8,
    tags: ['history', 'photography'],
    priceTier: 'medium',
  },
  {
    _id: 'hawa_mahal',
    name: 'Hawa Mahal',
    cityName: 'Jaipur',
    type: 'Palace',
    coordinates: { lat: 26.9239, lng: 75.8267 },
    timeRequired: 1,
    openingTime: '09:00',
    closingTime: '16:30',
    bestTimeOfDay: 'morning',
    rating: 4.5,
    tags: ['history', 'architecture'],
    priceTier: 'low',
  },
  {
    _id: 'city_palace_jaipur',
    name: 'City Palace',
    cityName: 'Jaipur',
    type: 'Palace',
    coordinates: { lat: 26.9258, lng: 75.8237 },
    timeRequired: 2,
    openingTime: '09:30',
    closingTime: '17:00',
    bestTimeOfDay: 'afternoon',
    rating: 4.6,
    tags: ['history', 'museum', 'senior-friendly'],
    priceTier: 'high',
  },
  {
    _id: 'jantar_mantar',
    name: 'Jantar Mantar',
    cityName: 'Jaipur',
    type: 'Observatory',
    coordinates: { lat: 26.9248, lng: 75.8246 },
    timeRequired: 1,
    openingTime: '09:00',
    closingTime: '16:30',
    bestTimeOfDay: 'any',
    rating: 4.4,
    tags: ['science', 'history', 'senior-friendly'],
    priceTier: 'low',
  },
  {
    _id: 'nahargarh_fort',
    name: 'Nahargarh Fort',
    cityName: 'Jaipur',
    type: 'Fort',
    coordinates: { lat: 26.9386, lng: 75.8163 },
    timeRequired: 2,
    openingTime: '10:00',
    closingTime: '22:00',
    bestTimeOfDay: 'evening',
    rating: 4.5,
    tags: ['views', 'sunset'],
    priceTier: 'medium',
  },

  // UDAIPUR
  {
    _id: 'city_palace_udaipur',
    name: 'City Palace',
    cityName: 'Udaipur',
    type: 'Palace',
    coordinates: { lat: 24.5764, lng: 73.6835 },
    timeRequired: 3,
    openingTime: '09:30',
    closingTime: '17:30',
    bestTimeOfDay: 'morning',
    rating: 4.7,
    tags: ['history', 'lake_view'],
    priceTier: 'high',
  },
  {
    _id: 'lake_pichola',
    name: 'Lake Pichola',
    cityName: 'Udaipur',
    type: 'Lake',
    coordinates: { lat: 24.5726, lng: 73.6744 },
    timeRequired: 2,
    openingTime: '00:00',
    closingTime: '23:59',
    bestTimeOfDay: 'evening',
    rating: 4.8,
    tags: ['nature', 'romantic', 'boating'],
    priceTier: 'medium',
  },
  {
    _id: 'saheliyon_ki_bari',
    name: 'Saheliyon Ki Bari',
    cityName: 'Udaipur',
    type: 'Garden',
    coordinates: { lat: 24.6033, lng: 73.6881 },
    timeRequired: 1,
    openingTime: '09:00',
    closingTime: '19:00',
    bestTimeOfDay: 'morning',
    rating: 4.3,
    tags: ['nature', 'senior-friendly', 'relaxed'],
    priceTier: 'low',
  },
  {
    _id: 'jagdish_temple',
    name: 'Jagdish Temple',
    cityName: 'Udaipur',
    type: 'Temple',
    coordinates: { lat: 24.5796, lng: 73.6844 },
    timeRequired: 0.5,
    openingTime: '05:00',
    closingTime: '21:00',
    bestTimeOfDay: 'morning',
    rating: 4.6,
    tags: ['religious', 'senior-friendly'],
    priceTier: 'free',
  },

  // JODHPUR
  {
    _id: 'mehrangarh_fort',
    name: 'Mehrangarh Fort',
    cityName: 'Jodhpur',
    type: 'Fort',
    coordinates: { lat: 26.2975, lng: 73.0185 },
    timeRequired: 3,
    openingTime: '09:00',
    closingTime: '17:00',
    bestTimeOfDay: 'morning',
    rating: 4.9,
    tags: ['history', 'views', 'must-visit'],
    priceTier: 'medium',
  },
  {
    _id: 'jaswant_thada',
    name: 'Jaswant Thada',
    cityName: 'Jodhpur',
    type: 'Monument',
    coordinates: { lat: 26.3040, lng: 73.0238 },
    timeRequired: 1,
    openingTime: '09:00',
    closingTime: '17:00',
    bestTimeOfDay: 'morning',
    rating: 4.5,
    tags: ['history', 'peaceful'],
    priceTier: 'low',
  },
  {
    _id: 'umaid_bhawan',
    name: 'Umaid Bhawan Palace',
    cityName: 'Jodhpur',
    type: 'Palace',
    coordinates: { lat: 26.2808, lng: 73.0474 },
    timeRequired: 2,
    openingTime: '10:00',
    closingTime: '16:30',
    bestTimeOfDay: 'any',
    rating: 4.6,
    tags: ['luxury', 'museum', 'history'],
    priceTier: 'high',
  },

  // JAISALMER
  {
    _id: 'jaisalmer_fort',
    name: 'Jaisalmer Fort',
    cityName: 'Jaisalmer',
    type: 'Fort',
    coordinates: { lat: 26.9124, lng: 70.9127 },
    timeRequired: 3,
    openingTime: '00:00',
    closingTime: '23:59', // Living fort
    bestTimeOfDay: 'morning',
    rating: 4.7,
    tags: ['history', 'walking', 'living_fort'],
    priceTier: 'free',
  },
  {
    _id: 'patwon_ki_haveli',
    name: 'Patwon Ki Haveli',
    cityName: 'Jaisalmer',
    type: 'Haveli',
    coordinates: { lat: 26.9152, lng: 70.9137 },
    timeRequired: 1.5,
    openingTime: '09:00',
    closingTime: '18:00',
    bestTimeOfDay: 'afternoon',
    rating: 4.5,
    tags: ['architecture', 'history'],
    priceTier: 'medium',
  },
  {
    _id: 'sam_sand_dunes',
    name: 'Sam Sand Dunes',
    cityName: 'Jaisalmer',
    type: 'Desert',
    coordinates: { lat: 26.8375, lng: 70.5283 },
    timeRequired: 4,
    openingTime: '00:00',
    closingTime: '23:59',
    bestTimeOfDay: 'evening',
    rating: 4.6,
    tags: ['nature', 'adventure', 'camel_ride', 'sunset'],
    priceTier: 'medium',
  }
];
