// This file provides curated data for the MVP (Rajasthan)
// It mimics the database queries for the sandbox environment where MongoDB is not available.

export const STATES = [
  {
    _id: 'RJ',
    code: 'RJ',
    name: 'Rajasthan',
    center: { lat: 26.5, lng: 73.8 },
    zoom: 7,
    description: 'The Land of Kings, featuring forts, deserts, and vibrant culture.',
    // Hawa Mahal, Jaipur
    imageUrl: 'https://images.unsplash.com/photo-1599661046289-e31897846e41?w=600&h=800&fit=crop',
  },
  {
    _id: 'KL',
    code: 'KL',
    name: 'Kerala',
    center: { lat: 10.8505, lng: 76.2711 },
    zoom: 7,
    description: "God's Own Country, known for its backwaters, beaches, and tea gardens.",
    // Kerala Backwaters with houseboat
    imageUrl: 'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=600&h=800&fit=crop',
  },
  {
    _id: 'GA',
    code: 'GA',
    name: 'Goa',
    center: { lat: 15.2993, lng: 74.1240 },
    zoom: 9,
    description: 'Famous for its beaches, Portuguese heritage, and vibrant nightlife.',
    // Goa Beach with palm trees
    imageUrl: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=600&h=800&fit=crop',
  },
  {
    _id: 'HP',
    code: 'HP',
    name: 'Himachal Pradesh',
    center: { lat: 31.1048, lng: 77.1734 },
    zoom: 7,
    description: "A mountain lover's paradise with snow-capped peaks and scenic valleys.",
    imageUrl: 'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=600&h=800&fit=crop',
  },
  {
    _id: 'UP',
    code: 'UP',
    name: 'Uttar Pradesh',
    center: { lat: 27.2046, lng: 80.3020 },
    zoom: 7,
    description: 'Home to the Taj Mahal, Varanasi ghats, and rich Mughal heritage.',
    imageUrl: 'https://images.unsplash.com/photo-1564507592333-c60657eea523?w=600&h=800&fit=crop',
  },
  {
    _id: 'MP',
    code: 'MP',
    name: 'Madhya Pradesh',
    center: { lat: 23.4733, lng: 77.9479 },
    zoom: 7,
    description: 'The Heart of India, with ancient temples, wildlife, and medieval cities.',
    imageUrl: 'https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?w=600&h=800&fit=crop',
  }
];

export const PACKAGES = [
  {
    id: 'royal-rajasthan',
    title: 'Royal Rajasthan Heritage',
    state: 'Rajasthan',
    days: 7,
    price: 35000,
    // Amber Fort, Jaipur
    image: 'https://images.unsplash.com/photo-1477587458883-47145ed94245?w=600&h=400&fit=crop',
    description: 'Experience the grandeur of forts and palaces in Jaipur, Jodhpur, and Udaipur.',
    tags: ['Heritage', 'Luxury', 'Culture']
  },
  {
    id: 'kerala-backwaters',
    title: 'Kerala Backwaters & Hills',
    state: 'Kerala',
    days: 5,
    price: 25000,
    // Munnar Tea Gardens
    image: 'https://images.unsplash.com/photo-1593693397690-362cb9666fc2?w=600&h=400&fit=crop',
    description: 'Relax on houseboats in Alleppey and explore the tea gardens of Munnar.',
    tags: ['Nature', 'Relaxation', 'Honeymoon']
  },
  {
    id: 'goa-beach-party',
    title: 'Goa Sun & Sand',
    state: 'Goa',
    days: 4,
    price: 15000,
    // Goa Beach Sunset
    image: 'https://images.unsplash.com/photo-1614082242765-7c98ca0f3df3?w=600&h=400&fit=crop',
    description: 'Enjoy the best beaches, water sports, and nightlife in North Goa.',
    tags: ['Beaches', 'Nightlife', 'Friends']
  }
];


export const CITIES = [
  // RAJASTHAN
  {
    _id: 'jaipur',
    name: 'Jaipur',
    stateCode: 'RAJASTHAN',
    coordinates: { lat: 26.9124, lng: 75.7873 },
    tier: 'tier1',
    description: 'The Pink City, famous for Hawa Mahal, Amer Fort, and City Palace.',
    idealDays: 2,
    // Hawa Mahal - iconic pink palace
    imageUrl: 'https://images.unsplash.com/photo-1599661046289-e31897846e41?w=400&h=400&fit=crop',
  },
  {
    _id: 'udaipur',
    name: 'Udaipur',
    stateCode: 'RAJASTHAN',
    coordinates: { lat: 24.5854, lng: 73.7125 },
    tier: 'tier1',
    description: 'The City of Lakes, known for its romantic setting and palaces.',
    idealDays: 2,
    // Lake Pichola with City Palace
    imageUrl: 'https://images.unsplash.com/photo-1568495248636-6432b97bd949?w=400&h=400&fit=crop',
  },
  {
    _id: 'jodhpur',
    name: 'Jodhpur',
    stateCode: 'RAJASTHAN',
    coordinates: { lat: 26.2389, lng: 73.0243 },
    tier: 'tier2',
    description: 'The Blue City, dominated by the massive Mehrangarh Fort.',
    idealDays: 2,
    // Blue City with Mehrangarh Fort
    imageUrl: 'https://images.unsplash.com/photo-1590449911964-b04b6b64731c?w=400&h=400&fit=crop',
  },
  {
    _id: 'jaisalmer',
    name: 'Jaisalmer',
    stateCode: 'RAJASTHAN',
    coordinates: { lat: 26.9157, lng: 70.9083 },
    tier: 'tier2',
    description: 'The Golden City, located in the heart of the Thar Desert.',
    idealDays: 2,
    // Jaisalmer Fort - Golden Fort
    imageUrl: 'https://images.unsplash.com/photo-1624806992066-5ffcf7ca186b?w=400&h=400&fit=crop',
  },
  // KERALA (Mock)
  {
    _id: 'munnar',
    name: 'Munnar',
    stateCode: 'KERALA',
    coordinates: { lat: 10.0889, lng: 77.0595 },
    tier: 'tier2',
    description: 'A hill station famous for its tea estates and misty mountains.',
    idealDays: 2,
    imageUrl: 'https://images.unsplash.com/photo-1596323674681-424d86b856b3?auto=format&fit=crop&q=80',
  },
  {
    _id: 'alleppey',
    name: 'Alleppey',
    stateCode: 'KERALA',
    coordinates: { lat: 9.4981, lng: 76.3388 },
    tier: 'tier2',
    description: 'Known as the Venice of the East, famous for houseboat cruises.',
    idealDays: 1,
    imageUrl: 'https://images.unsplash.com/photo-1593693397690-362cb9666fc2?auto=format&fit=crop&q=80',
  },
  // GOA
  {
    _id: 'north_goa',
    name: 'North Goa',
    stateCode: 'GOA',
    coordinates: { lat: 15.5449, lng: 73.7551 },
    tier: 'tier1',
    description: 'Famous for beaches, nightlife, and water sports.',
    idealDays: 2,
    imageUrl: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&q=80',
  },
  {
    _id: 'old_goa',
    name: 'Old Goa',
    stateCode: 'GOA',
    coordinates: { lat: 15.5009, lng: 73.9116 },
    tier: 'tier2',
    description: 'Historic capital with UNESCO World Heritage churches.',
    idealDays: 1,
    imageUrl: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&q=80',
  },
  // MAHARASHTRA
  {
    _id: 'mumbai',
    name: 'Mumbai',
    stateCode: 'MAHARASHTR',
    coordinates: { lat: 18.9220, lng: 72.8347 },
    tier: 'tier1',
    description: 'The City of Dreams, financial capital of India.',
    idealDays: 3,
    imageUrl: 'https://images.unsplash.com/photo-1570168007204-dfb528c6958f?auto=format&fit=crop&q=80',
  },
  {
    _id: 'aurangabad',
    name: 'Aurangabad',
    stateCode: 'MAHARASHTR',
    coordinates: { lat: 19.8762, lng: 75.3433 },
    tier: 'tier2',
    description: 'Gateway to Ajanta and Ellora caves.',
    idealDays: 2,
    imageUrl: 'https://images.unsplash.com/photo-1570168007204-dfb528c6958f?auto=format&fit=crop&q=80',
  },
  // TAMIL NADU
  {
    _id: 'chennai',
    name: 'Chennai',
    stateCode: 'TAMIL_NADU',
    coordinates: { lat: 13.0827, lng: 80.2707 },
    tier: 'tier1',
    description: 'Cultural capital of South India with rich heritage.',
    idealDays: 2,
    imageUrl: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&q=80',
  },
  {
    _id: 'madurai',
    name: 'Madurai',
    stateCode: 'TAMIL_NADU',
    coordinates: { lat: 9.9252, lng: 78.1198 },
    tier: 'tier2',
    description: 'One of the oldest cities, famous for Meenakshi Temple.',
    idealDays: 2,
    imageUrl: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&q=80',
  },
  // WEST BENGAL
  {
    _id: 'kolkata',
    name: 'Kolkata',
    stateCode: 'WEST_BENGA',
    coordinates: { lat: 22.5726, lng: 88.3639 },
    tier: 'tier1',
    description: 'City of Joy, known for its colonial heritage and culture.',
    idealDays: 3,
    imageUrl: 'https://images.unsplash.com/photo-1558431382-27e303142255?auto=format&fit=crop&q=80',
  },
  // KARNATAKA
  {
    _id: 'mysore',
    name: 'Mysore',
    stateCode: 'KARNATAKA',
    coordinates: { lat: 12.2958, lng: 76.6394 },
    tier: 'tier2',
    description: 'City of Palaces, known for its royal heritage.',
    idealDays: 2,
    imageUrl: 'https://images.unsplash.com/photo-1600100397608-6c5f54b32ea7?auto=format&fit=crop&q=80',
  },
  {
    _id: 'hampi_city',
    name: 'Hampi',
    stateCode: 'KARNATAKA',
    coordinates: { lat: 15.3350, lng: 76.4600 },
    tier: 'tier2',
    description: 'UNESCO World Heritage Site with ancient Vijayanagara ruins.',
    idealDays: 2,
    imageUrl: 'https://images.unsplash.com/photo-1600100397608-6c5f54b32ea7?auto=format&fit=crop&q=80',
  },
  // GUJARAT
  {
    _id: 'kutch',
    name: 'Kutch',
    stateCode: 'GUJARAT',
    coordinates: { lat: 23.7337, lng: 69.8597 },
    tier: 'tier2',
    description: 'Famous for the white salt desert Rann of Kutch.',
    idealDays: 2,
    imageUrl: 'https://images.unsplash.com/photo-1589308078059-be1415eab4c3?auto=format&fit=crop&q=80',
  },
  {
    _id: 'kevadia',
    name: 'Kevadia',
    stateCode: 'GUJARAT',
    coordinates: { lat: 21.8380, lng: 73.7191 },
    tier: 'tier2',
    description: 'Home to the Statue of Unity, the world\'s tallest statue.',
    idealDays: 1,
    imageUrl: 'https://images.unsplash.com/photo-1589308078059-be1415eab4c3?auto=format&fit=crop&q=80',
  },
  {
    _id: 'ahmedabad',
    name: 'Ahmedabad',
    stateCode: 'GUJARAT',
    coordinates: { lat: 23.0225, lng: 72.5714 },
    tier: 'tier1',
    description: 'UNESCO Heritage City with Sabarmati Ashram and vibrant street food.',
    idealDays: 2,
    imageUrl: 'https://images.unsplash.com/photo-1595658658481-d53d3f999875?auto=format&fit=crop&q=80',
  },
  {
    _id: 'dwarka',
    name: 'Dwarka',
    stateCode: 'GUJARAT',
    coordinates: { lat: 22.2442, lng: 68.9685 },
    tier: 'tier2',
    description: 'Sacred city of Lord Krishna, one of the four Char Dhams.',
    idealDays: 1,
    imageUrl: 'https://images.unsplash.com/photo-1589308078059-be1415eab4c3?auto=format&fit=crop&q=80',
  },
  {
    _id: 'somnath',
    name: 'Somnath',
    stateCode: 'GUJARAT',
    coordinates: { lat: 20.8880, lng: 70.4013 },
    tier: 'tier2',
    description: 'Home to one of the twelve Jyotirlingas, a sacred pilgrimage site.',
    idealDays: 1,
    imageUrl: 'https://images.unsplash.com/photo-1589308078059-be1415eab4c3?auto=format&fit=crop&q=80',
  },
  // UTTAR PRADESH
  {
    _id: 'agra',
    name: 'Agra',
    stateCode: 'UTTAR_PRADESH',
    coordinates: { lat: 27.1767, lng: 78.0081 },
    tier: 'tier1',
    description: 'Home to the iconic Taj Mahal and Mughal heritage monuments.',
    idealDays: 2,
    imageUrl: 'https://images.unsplash.com/photo-1564507592333-c60657eea523?auto=format&fit=crop&q=80',
  },
  {
    _id: 'varanasi',
    name: 'Varanasi',
    stateCode: 'UTTAR_PRADESH',
    coordinates: { lat: 25.3176, lng: 83.0068 },
    tier: 'tier1',
    description: 'The spiritual capital of India, one of the oldest living cities.',
    idealDays: 2,
    imageUrl: 'https://images.unsplash.com/photo-1561361513-2d000a50f0dc?auto=format&fit=crop&q=80',
  },
  {
    _id: 'lucknow',
    name: 'Lucknow',
    stateCode: 'UTTAR_PRADESH',
    coordinates: { lat: 26.8467, lng: 80.9462 },
    tier: 'tier1',
    description: 'City of Nawabs, famous for Mughal architecture and Awadhi cuisine.',
    idealDays: 2,
    imageUrl: 'https://images.unsplash.com/photo-1564507592333-c60657eea523?auto=format&fit=crop&q=80',
  },
  {
    _id: 'mathura',
    name: 'Mathura',
    stateCode: 'UTTAR_PRADESH',
    coordinates: { lat: 27.4924, lng: 77.6737 },
    tier: 'tier2',
    description: 'Birthplace of Lord Krishna, a major Hindu pilgrimage center.',
    idealDays: 1,
    imageUrl: 'https://images.unsplash.com/photo-1564507592333-c60657eea523?auto=format&fit=crop&q=80',
  },
  // MADHYA PRADESH
  {
    _id: 'bhopal',
    name: 'Bhopal',
    stateCode: 'MADHYA_PRADESH',
    coordinates: { lat: 23.2599, lng: 77.4126 },
    tier: 'tier1',
    description: 'City of Lakes, blending Mughal heritage with modern culture.',
    idealDays: 2,
    imageUrl: 'https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?auto=format&fit=crop&q=80',
  },
  {
    _id: 'khajuraho',
    name: 'Khajuraho',
    stateCode: 'MADHYA_PRADESH',
    coordinates: { lat: 24.8318, lng: 79.9199 },
    tier: 'tier2',
    description: 'UNESCO site famous for exquisite temple sculptures.',
    idealDays: 2,
    imageUrl: 'https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?auto=format&fit=crop&q=80',
  },
  {
    _id: 'ujjain',
    name: 'Ujjain',
    stateCode: 'MADHYA_PRADESH',
    coordinates: { lat: 23.1765, lng: 75.7885 },
    tier: 'tier2',
    description: 'Ancient city of Mahakaleshwar, one of the twelve Jyotirlingas.',
    idealDays: 1,
    imageUrl: 'https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?auto=format&fit=crop&q=80',
  },
  {
    _id: 'orchha',
    name: 'Orchha',
    stateCode: 'MADHYA_PRADESH',
    coordinates: { lat: 25.3519, lng: 78.6419 },
    tier: 'tier2',
    description: 'Medieval town with stunning Bundela-era palaces and temples.',
    idealDays: 1,
    imageUrl: 'https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?auto=format&fit=crop&q=80',
  },
  // KERALA (additional)
  {
    _id: 'kochi',
    name: 'Kochi',
    stateCode: 'KERALA',
    coordinates: { lat: 9.9312, lng: 76.2673 },
    tier: 'tier1',
    description: 'Queen of the Arabian Sea, a cosmopolitan port city with colonial history.',
    idealDays: 2,
    imageUrl: 'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?auto=format&fit=crop&q=80',
  }
];

export const PLACES = [
  // JAIPUR
  {
    _id: 'amber_fort',
    name: 'Amber Fort',
    cityName: 'Jaipur',
    type: 'Fort',
    coordinates: { lat: 26.9855, lng: 75.8513 },
    timeRequired: 3,
    openingTime: '08:00',
    closingTime: '17:30',
    bestTimeOfDay: 'morning',
    rating: 4.8,
    tags: ['history', 'photography'],
    priceTier: 'medium',
    thumbnailUrl: 'https://images.unsplash.com/photo-1599661046289-e31897846e41?w=400&h=300&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1599661046289-e31897846e41?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1477587458883-47145ed94245?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1524492412937-b28074a5d7da?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1602508451687-5765c3c82c57?w=800&h=600&fit=crop',
    ],
  },
  {
    _id: 'hawa_mahal',
    name: 'Hawa Mahal',
    cityName: 'Jaipur',
    type: 'Palace',
    coordinates: { lat: 26.9239, lng: 75.8267 },
    timeRequired: 1,
    openingTime: '09:00',
    closingTime: '16:30',
    bestTimeOfDay: 'morning',
    rating: 4.5,
    tags: ['history', 'architecture'],
    priceTier: 'low',
    thumbnailUrl: 'https://images.unsplash.com/photo-1599661046827-dacff0c0f09a?w=400&h=300&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1599661046827-dacff0c0f09a?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1570168007204-dfb528c6958f?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1587474260584-136574528ed5?w=800&h=600&fit=crop',
    ],
  },
  {
    _id: 'city_palace_jaipur',
    name: 'City Palace',
    cityName: 'Jaipur',
    type: 'Palace',
    coordinates: { lat: 26.9258, lng: 75.8237 },
    timeRequired: 2,
    openingTime: '09:30',
    closingTime: '17:00',
    bestTimeOfDay: 'afternoon',
    rating: 4.6,
    tags: ['history', 'museum', 'senior-friendly'],
    priceTier: 'high',
    thumbnailUrl: 'https://images.unsplash.com/photo-1603204077779-bed963ea7d0e?w=400&h=300&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1603204077779-bed963ea7d0e?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1585506942812-e72b29cef752?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1614082242765-7c98ca0f3df3?w=800&h=600&fit=crop',
    ],
  },
  {
    _id: 'jantar_mantar',
    name: 'Jantar Mantar',
    cityName: 'Jaipur',
    type: 'Observatory',
    coordinates: { lat: 26.9248, lng: 75.8246 },
    timeRequired: 1,
    openingTime: '09:00',
    closingTime: '16:30',
    bestTimeOfDay: 'any',
    rating: 4.4,
    tags: ['science', 'history', 'senior-friendly'],
    priceTier: 'low',
  },
  {
    _id: 'nahargarh_fort',
    name: 'Nahargarh Fort',
    cityName: 'Jaipur',
    type: 'Fort',
    coordinates: { lat: 26.9386, lng: 75.8163 },
    timeRequired: 2,
    openingTime: '10:00',
    closingTime: '22:00',
    bestTimeOfDay: 'evening',
    rating: 4.5,
    tags: ['views', 'sunset'],
    priceTier: 'medium',
  },

  // UDAIPUR
  {
    _id: 'city_palace_udaipur',
    name: 'City Palace',
    cityName: 'Udaipur',
    type: 'Palace',
    coordinates: { lat: 24.5764, lng: 73.6835 },
    timeRequired: 3,
    openingTime: '09:30',
    closingTime: '17:30',
    bestTimeOfDay: 'morning',
    rating: 4.7,
    tags: ['history', 'lake_view'],
    priceTier: 'high',
    thumbnailUrl: 'https://images.unsplash.com/photo-1585506942812-e72b29cef752?w=400&h=300&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1585506942812-e72b29cef752?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1614082242765-7c98ca0f3df3?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1603204077779-bed963ea7d0e?w=800&h=600&fit=crop',
    ],
  },
  {
    _id: 'lake_pichola',
    name: 'Lake Pichola',
    cityName: 'Udaipur',
    type: 'Lake',
    coordinates: { lat: 24.5726, lng: 73.6744 },
    timeRequired: 2,
    openingTime: '00:00',
    closingTime: '23:59',
    bestTimeOfDay: 'evening',
    rating: 4.8,
    tags: ['nature', 'romantic', 'boating'],
    priceTier: 'medium',
  },
  {
    _id: 'saheliyon_ki_bari',
    name: 'Saheliyon Ki Bari',
    cityName: 'Udaipur',
    type: 'Garden',
    coordinates: { lat: 24.6033, lng: 73.6881 },
    timeRequired: 1,
    openingTime: '09:00',
    closingTime: '19:00',
    bestTimeOfDay: 'morning',
    rating: 4.3,
    tags: ['nature', 'senior-friendly', 'relaxed'],
    priceTier: 'low',
  },
  {
    _id: 'jagdish_temple',
    name: 'Jagdish Temple',
    cityName: 'Udaipur',
    type: 'Temple',
    coordinates: { lat: 24.5796, lng: 73.6844 },
    timeRequired: 0.5,
    openingTime: '05:00',
    closingTime: '21:00',
    bestTimeOfDay: 'morning',
    rating: 4.6,
    tags: ['religious', 'senior-friendly'],
    priceTier: 'free',
  },

  // JODHPUR
  {
    _id: 'mehrangarh_fort',
    name: 'Mehrangarh Fort',
    cityName: 'Jodhpur',
    type: 'Fort',
    coordinates: { lat: 26.2975, lng: 73.0185 },
    timeRequired: 3,
    openingTime: '09:00',
    closingTime: '17:00',
    bestTimeOfDay: 'morning',
    rating: 4.9,
    tags: ['history', 'views', 'must-visit'],
    priceTier: 'medium',
    thumbnailUrl: 'https://images.unsplash.com/photo-1590449911964-b04b6b64731c?w=400&h=300&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1590449911964-b04b6b64731c?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1524492412937-b28074a5d7da?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1602508451687-5765c3c82c57?w=800&h=600&fit=crop',
    ],
  },
  {
    _id: 'jaswant_thada',
    name: 'Jaswant Thada',
    cityName: 'Jodhpur',
    type: 'Monument',
    coordinates: { lat: 26.3040, lng: 73.0238 },
    timeRequired: 1,
    openingTime: '09:00',
    closingTime: '17:00',
    bestTimeOfDay: 'morning',
    rating: 4.5,
    tags: ['history', 'peaceful'],
    priceTier: 'low',
  },
  {
    _id: 'umaid_bhawan',
    name: 'Umaid Bhawan Palace',
    cityName: 'Jodhpur',
    type: 'Palace',
    coordinates: { lat: 26.2808, lng: 73.0474 },
    timeRequired: 2,
    openingTime: '10:00',
    closingTime: '16:30',
    bestTimeOfDay: 'any',
    rating: 4.6,
    tags: ['luxury', 'museum', 'history'],
    priceTier: 'high',
  },

  // JAISALMER
  {
    _id: 'jaisalmer_fort',
    name: 'Jaisalmer Fort',
    cityName: 'Jaisalmer',
    type: 'Fort',
    coordinates: { lat: 26.9124, lng: 70.9127 },
    timeRequired: 3,
    openingTime: '00:00',
    closingTime: '23:59', // Living fort
    bestTimeOfDay: 'morning',
    rating: 4.7,
    tags: ['history', 'walking', 'living_fort'],
    priceTier: 'free',
    thumbnailUrl: 'https://images.unsplash.com/photo-1598521868685-eb06c8b2e3c0?w=400&h=300&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1598521868685-eb06c8b2e3c0?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1602508451687-5765c3c82c57?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1477587458883-47145ed94245?w=800&h=600&fit=crop',
    ],
  },
  {
    _id: 'patwon_ki_haveli',
    name: 'Patwon Ki Haveli',
    cityName: 'Jaisalmer',
    type: 'Haveli',
    coordinates: { lat: 26.9152, lng: 70.9137 },
    timeRequired: 1.5,
    openingTime: '09:00',
    closingTime: '18:00',
    bestTimeOfDay: 'afternoon',
    rating: 4.5,
    tags: ['architecture', 'history'],
    priceTier: 'medium',
  },
  {
    _id: 'sam_sand_dunes',
    name: 'Sam Sand Dunes',
    cityName: 'Jaisalmer',
    type: 'Desert',
    coordinates: { lat: 26.8375, lng: 70.5283 },
    timeRequired: 4,
    openingTime: '00:00',
    closingTime: '23:59',
    bestTimeOfDay: 'evening',
    rating: 4.6,
    tags: ['nature', 'adventure', 'camel_ride', 'sunset'],
    priceTier: 'medium',
  },

  // KERALA PLACES (Mock)
  {
    _id: 'tea_museum',
    name: 'Tea Museum',
    cityName: 'Munnar',
    type: 'Museum',
    coordinates: { lat: 10.0889, lng: 77.0595 },
    timeRequired: 1,
    openingTime: '09:00',
    closingTime: '17:00',
    bestTimeOfDay: 'morning',
    rating: 4.4,
    tags: ['history', 'nature'],
    priceTier: 'low',
  },
  {
    _id: 'alleppey_backwaters',
    name: 'Alleppey Backwaters',
    cityName: 'Alleppey',
    type: 'Lake',
    coordinates: { lat: 9.4981, lng: 76.3388 },
    timeRequired: 4,
    openingTime: '00:00',
    closingTime: '23:59',
    bestTimeOfDay: 'evening',
    rating: 4.8,
    tags: ['nature', 'romantic'],
    priceTier: 'medium',
  },

  // GOA PLACES
  {
    _id: 'calangute_beach',
    name: 'Calangute Beach',
    cityName: 'North Goa',
    type: 'Beach',
    coordinates: { lat: 15.5449, lng: 73.7551 },
    timeRequired: 3,
    openingTime: '00:00',
    closingTime: '23:59',
    bestTimeOfDay: 'evening',
    rating: 4.3,
    tags: ['beach', 'water_sports', 'nightlife'],
    priceTier: 'low',
  },
  {
    _id: 'basilica_bom_jesus',
    name: 'Basilica of Bom Jesus',
    cityName: 'Old Goa',
    type: 'Church',
    coordinates: { lat: 15.5009, lng: 73.9116 },
    timeRequired: 1,
    openingTime: '09:00',
    closingTime: '18:30',
    bestTimeOfDay: 'morning',
    rating: 4.6,
    tags: ['heritage', 'religious', 'UNESCO'],
    priceTier: 'free',
  },

  // MAHARASHTRA PLACES
  {
    _id: 'gateway_of_india',
    name: 'Gateway of India',
    cityName: 'Mumbai',
    type: 'Monument',
    coordinates: { lat: 18.9220, lng: 72.8347 },
    timeRequired: 1,
    openingTime: '00:00',
    closingTime: '23:59',
    bestTimeOfDay: 'evening',
    rating: 4.5,
    tags: ['heritage', 'landmark'],
    priceTier: 'free',
  },
  {
    _id: 'ajanta_caves',
    name: 'Ajanta Caves',
    cityName: 'Aurangabad',
    type: 'Cave',
    coordinates: { lat: 20.5519, lng: 75.7033 },
    timeRequired: 4,
    openingTime: '09:00',
    closingTime: '17:00',
    bestTimeOfDay: 'morning',
    rating: 4.7,
    tags: ['heritage', 'UNESCO', 'history'],
    priceTier: 'medium',
  },

  // TAMIL NADU PLACES
  {
    _id: 'meenakshi_temple',
    name: 'Meenakshi Amman Temple',
    cityName: 'Madurai',
    type: 'Temple',
    coordinates: { lat: 9.9195, lng: 78.1193 },
    timeRequired: 2,
    openingTime: '05:00',
    closingTime: '21:00',
    bestTimeOfDay: 'morning',
    rating: 4.8,
    tags: ['religious', 'heritage', 'architecture'],
    priceTier: 'free',
  },
  {
    _id: 'marina_beach',
    name: 'Marina Beach',
    cityName: 'Chennai',
    type: 'Beach',
    coordinates: { lat: 13.0500, lng: 80.2824 },
    timeRequired: 2,
    openingTime: '00:00',
    closingTime: '23:59',
    bestTimeOfDay: 'evening',
    rating: 4.4,
    tags: ['beach', 'relaxation'],
    priceTier: 'free',
  },

  // WEST BENGAL PLACES
  {
    _id: 'victoria_memorial',
    name: 'Victoria Memorial',
    cityName: 'Kolkata',
    type: 'Monument',
    coordinates: { lat: 22.5448, lng: 88.3426 },
    timeRequired: 2,
    openingTime: '10:00',
    closingTime: '18:00',
    bestTimeOfDay: 'afternoon',
    rating: 4.7,
    tags: ['heritage', 'museum', 'gardens'],
    priceTier: 'medium',
  },
  {
    _id: 'howrah_bridge',
    name: 'Howrah Bridge',
    cityName: 'Kolkata',
    type: 'Landmark',
    coordinates: { lat: 22.5851, lng: 88.3468 },
    timeRequired: 1,
    openingTime: '00:00',
    closingTime: '23:59',
    bestTimeOfDay: 'evening',
    rating: 4.5,
    tags: ['landmark', 'iconic'],
    priceTier: 'free',
  },

  // KARNATAKA PLACES
  {
    _id: 'mysore_palace',
    name: 'Mysore Palace',
    cityName: 'Mysore',
    type: 'Palace',
    coordinates: { lat: 12.3052, lng: 76.6552 },
    timeRequired: 2,
    openingTime: '10:00',
    closingTime: '17:30',
    bestTimeOfDay: 'morning',
    rating: 4.7,
    tags: ['heritage', 'architecture', 'royal'],
    priceTier: 'medium',
  },
  {
    _id: 'hampi',
    name: 'Hampi Ruins',
    cityName: 'Hampi',
    type: 'Heritage',
    coordinates: { lat: 15.3350, lng: 76.4600 },
    timeRequired: 6,
    openingTime: '06:00',
    closingTime: '18:00',
    bestTimeOfDay: 'morning',
    rating: 4.8,
    tags: ['heritage', 'UNESCO', 'history'],
    priceTier: 'low',
  },

  // GUJARAT PLACES
  {
    _id: 'statue_of_unity',
    name: 'Statue of Unity',
    cityName: 'Kevadia',
    type: 'Monument',
    coordinates: { lat: 21.8380, lng: 73.7191 },
    timeRequired: 3,
    openingTime: '08:00',
    closingTime: '18:00',
    bestTimeOfDay: 'morning',
    rating: 4.6,
    tags: ['landmark', 'modern', 'views'],
    priceTier: 'medium',
  },
  {
    _id: 'rann_of_kutch',
    name: 'Rann of Kutch',
    cityName: 'Kutch',
    type: 'Desert',
    coordinates: { lat: 23.7337, lng: 69.8597 },
    timeRequired: 4,
    openingTime: '00:00',
    closingTime: '23:59',
    bestTimeOfDay: 'evening',
    rating: 4.7,
    tags: ['nature', 'desert', 'unique'],
    priceTier: 'medium',
  },
  // AHMEDABAD
  { _id: 'sabarmati_ashram', name: 'Sabarmati Ashram', cityName: 'Ahmedabad', type: 'Historical', coordinates: { lat: 23.0607, lng: 72.5812 }, timeRequired: 1.5, openingTime: '08:30', closingTime: '18:30', bestTimeOfDay: 'morning', rating: 4.7, tags: ['history', 'gandhi', 'heritage'], priceTier: 'free' },
  { _id: 'adalaj_stepwell', name: 'Adalaj Stepwell', cityName: 'Ahmedabad', type: 'Historical', coordinates: { lat: 23.1666, lng: 72.5822 }, timeRequired: 1, openingTime: '06:00', closingTime: '18:00', bestTimeOfDay: 'morning', rating: 4.5, tags: ['architecture', 'heritage'], priceTier: 'free' },
  { _id: 'sidi_saiyyed_mosque', name: 'Sidi Saiyyed Mosque', cityName: 'Ahmedabad', type: 'Religious', coordinates: { lat: 23.0258, lng: 72.5793 }, timeRequired: 0.5, openingTime: '06:00', closingTime: '20:00', bestTimeOfDay: 'morning', rating: 4.4, tags: ['architecture', 'religious'], priceTier: 'free' },
  { _id: 'kankaria_lake', name: 'Kankaria Lake', cityName: 'Ahmedabad', type: 'Nature', coordinates: { lat: 22.9948, lng: 72.6007 }, timeRequired: 2, openingTime: '09:00', closingTime: '22:00', bestTimeOfDay: 'evening', rating: 4.3, tags: ['nature', 'family', 'recreation'], priceTier: 'low' },
  { _id: 'calico_museum', name: 'Calico Museum of Textiles', cityName: 'Ahmedabad', type: 'Museum', coordinates: { lat: 23.0402, lng: 72.5875 }, timeRequired: 2, openingTime: '10:00', closingTime: '17:00', bestTimeOfDay: 'morning', rating: 4.6, tags: ['museum', 'textiles', 'art'], priceTier: 'low' },
  // DWARKA
  { _id: 'dwarkadhish_temple', name: 'Dwarkadhish Temple', cityName: 'Dwarka', type: 'Religious', coordinates: { lat: 22.2376, lng: 68.9674 }, timeRequired: 1.5, openingTime: '06:00', closingTime: '21:00', bestTimeOfDay: 'morning', rating: 4.8, tags: ['religious', 'heritage', 'pilgrimage'], priceTier: 'free' },
  { _id: 'nageshwar_jyotirlinga', name: 'Nageshwar Jyotirlinga', cityName: 'Dwarka', type: 'Religious', coordinates: { lat: 22.3329, lng: 68.9625 }, timeRequired: 1, openingTime: '06:00', closingTime: '20:00', bestTimeOfDay: 'morning', rating: 4.5, tags: ['religious', 'pilgrimage'], priceTier: 'free' },
  { _id: 'bet_dwarka', name: 'Bet Dwarka', cityName: 'Dwarka', type: 'Island', coordinates: { lat: 22.4548, lng: 69.0824 }, timeRequired: 3, openingTime: '08:00', closingTime: '17:00', bestTimeOfDay: 'morning', rating: 4.4, tags: ['island', 'religious', 'boat-ride'], priceTier: 'medium' },
  { _id: 'rukmini_temple', name: 'Rukmini Devi Temple', cityName: 'Dwarka', type: 'Religious', coordinates: { lat: 22.2541, lng: 68.9387 }, timeRequired: 0.5, openingTime: '06:00', closingTime: '19:00', bestTimeOfDay: 'morning', rating: 4.2, tags: ['religious', 'heritage'], priceTier: 'free' },
  { _id: 'dwarka_beach', name: 'Dwarka Beach', cityName: 'Dwarka', type: 'Beach', coordinates: { lat: 22.2350, lng: 68.9650 }, timeRequired: 1.5, openingTime: '00:00', closingTime: '23:59', bestTimeOfDay: 'evening', rating: 4.1, tags: ['nature', 'beach', 'sunset'], priceTier: 'free' },
  // SOMNATH
  { _id: 'somnath_temple', name: 'Somnath Temple', cityName: 'Somnath', type: 'Religious', coordinates: { lat: 20.8880, lng: 70.4013 }, timeRequired: 1.5, openingTime: '06:00', closingTime: '21:00', bestTimeOfDay: 'evening', rating: 4.9, tags: ['religious', 'pilgrimage', 'jyotirlinga'], priceTier: 'free' },
  { _id: 'somnath_beach', name: 'Somnath Beach', cityName: 'Somnath', type: 'Beach', coordinates: { lat: 20.8870, lng: 70.3990 }, timeRequired: 1, openingTime: '00:00', closingTime: '23:59', bestTimeOfDay: 'evening', rating: 4.2, tags: ['beach', 'sunset', 'nature'], priceTier: 'free' },
  { _id: 'bhalka_tirth', name: 'Bhalka Tirth', cityName: 'Somnath', type: 'Religious', coordinates: { lat: 20.8710, lng: 70.3930 }, timeRequired: 0.5, openingTime: '06:00', closingTime: '19:00', bestTimeOfDay: 'morning', rating: 4.0, tags: ['religious', 'mythology'], priceTier: 'free' },
  { _id: 'triveni_sangam_somnath', name: 'Triveni Sangam', cityName: 'Somnath', type: 'Nature', coordinates: { lat: 20.8900, lng: 70.4050 }, timeRequired: 1, openingTime: '00:00', closingTime: '23:59', bestTimeOfDay: 'morning', rating: 4.3, tags: ['nature', 'river', 'sacred'], priceTier: 'free' },
  { _id: 'somnath_museum', name: 'Prabhas Patan Museum', cityName: 'Somnath', type: 'Museum', coordinates: { lat: 20.8895, lng: 70.4020 }, timeRequired: 1, openingTime: '09:00', closingTime: '17:00', bestTimeOfDay: 'morning', rating: 4.1, tags: ['museum', 'history', 'archaeology'], priceTier: 'low' },
  // AGRA
  { _id: 'taj_mahal', name: 'Taj Mahal', cityName: 'Agra', type: 'Monument', coordinates: { lat: 27.1751, lng: 78.0421 }, timeRequired: 3, openingTime: '06:00', closingTime: '18:30', bestTimeOfDay: 'morning', rating: 4.9, tags: ['wonder', 'heritage', 'mughal', 'UNESCO'], priceTier: 'high' },
  { _id: 'agra_fort', name: 'Agra Fort', cityName: 'Agra', type: 'Fort', coordinates: { lat: 27.1795, lng: 78.0211 }, timeRequired: 2, openingTime: '06:00', closingTime: '18:00', bestTimeOfDay: 'morning', rating: 4.7, tags: ['fort', 'mughal', 'UNESCO'], priceTier: 'medium' },
  { _id: 'fatehpur_sikri', name: 'Fatehpur Sikri', cityName: 'Agra', type: 'Historical', coordinates: { lat: 27.0940, lng: 77.6610 }, timeRequired: 3, openingTime: '06:00', closingTime: '18:00', bestTimeOfDay: 'morning', rating: 4.6, tags: ['heritage', 'mughal', 'UNESCO'], priceTier: 'medium' },
  { _id: 'mehtab_bagh', name: 'Mehtab Bagh', cityName: 'Agra', type: 'Garden', coordinates: { lat: 27.1788, lng: 78.0447 }, timeRequired: 1, openingTime: '06:00', closingTime: '18:00', bestTimeOfDay: 'evening', rating: 4.4, tags: ['garden', 'view', 'photography'], priceTier: 'low' },
  { _id: 'itimad_ud_daulah', name: 'Itimad-ud-Daulah', cityName: 'Agra', type: 'Monument', coordinates: { lat: 27.1927, lng: 78.0306 }, timeRequired: 1, openingTime: '06:00', closingTime: '18:00', bestTimeOfDay: 'morning', rating: 4.5, tags: ['heritage', 'mughal', 'baby-taj'], priceTier: 'medium' },
  // VARANASI
  { _id: 'dashashwamedh_ghat', name: 'Dashashwamedh Ghat', cityName: 'Varanasi', type: 'Ghat', coordinates: { lat: 25.3109, lng: 83.0107 }, timeRequired: 2, openingTime: '04:00', closingTime: '22:00', bestTimeOfDay: 'evening', rating: 4.8, tags: ['ghat', 'spiritual', 'ganga-aarti'], priceTier: 'free' },
  { _id: 'kashi_vishwanath', name: 'Kashi Vishwanath Temple', cityName: 'Varanasi', type: 'Religious', coordinates: { lat: 25.3109, lng: 83.0107 }, timeRequired: 1.5, openingTime: '03:00', closingTime: '23:00', bestTimeOfDay: 'morning', rating: 4.9, tags: ['religious', 'jyotirlinga', 'pilgrimage'], priceTier: 'free' },
  { _id: 'sarnath', name: 'Sarnath', cityName: 'Varanasi', type: 'Historical', coordinates: { lat: 25.3814, lng: 83.0230 }, timeRequired: 2.5, openingTime: '06:00', closingTime: '17:00', bestTimeOfDay: 'morning', rating: 4.6, tags: ['buddhist', 'heritage', 'museum'], priceTier: 'low' },
  { _id: 'assi_ghat', name: 'Assi Ghat', cityName: 'Varanasi', type: 'Ghat', coordinates: { lat: 25.2926, lng: 83.0040 }, timeRequired: 1.5, openingTime: '04:00', closingTime: '22:00', bestTimeOfDay: 'morning', rating: 4.5, tags: ['ghat', 'spiritual', 'sunrise'], priceTier: 'free' },
  { _id: 'ramnagar_fort', name: 'Ramnagar Fort', cityName: 'Varanasi', type: 'Fort', coordinates: { lat: 25.2877, lng: 83.0293 }, timeRequired: 1.5, openingTime: '10:00', closingTime: '17:00', bestTimeOfDay: 'afternoon', rating: 4.2, tags: ['fort', 'museum', 'heritage'], priceTier: 'low' },
  // LUCKNOW
  { _id: 'bara_imambara', name: 'Bara Imambara', cityName: 'Lucknow', type: 'Historical', coordinates: { lat: 26.8690, lng: 80.9136 }, timeRequired: 2, openingTime: '06:00', closingTime: '17:00', bestTimeOfDay: 'morning', rating: 4.7, tags: ['heritage', 'mughal', 'labyrinth'], priceTier: 'low' },
  { _id: 'chhota_imambara', name: 'Chhota Imambara', cityName: 'Lucknow', type: 'Historical', coordinates: { lat: 26.8693, lng: 80.9144 }, timeRequired: 1, openingTime: '06:00', closingTime: '17:00', bestTimeOfDay: 'morning', rating: 4.5, tags: ['heritage', 'mughal', 'architecture'], priceTier: 'low' },
  { _id: 'british_residency', name: 'British Residency', cityName: 'Lucknow', type: 'Historical', coordinates: { lat: 26.8641, lng: 80.9222 }, timeRequired: 1.5, openingTime: '06:00', closingTime: '18:00', bestTimeOfDay: 'morning', rating: 4.3, tags: ['heritage', 'colonial', 'history'], priceTier: 'low' },
  { _id: 'lucknow_zoo', name: 'Lucknow Zoo', cityName: 'Lucknow', type: 'Nature', coordinates: { lat: 26.8509, lng: 80.9346 }, timeRequired: 2.5, openingTime: '08:30', closingTime: '17:30', bestTimeOfDay: 'morning', rating: 4.2, tags: ['zoo', 'family', 'nature'], priceTier: 'low' },
  { _id: 'ambedkar_park', name: 'Ambedkar Memorial Park', cityName: 'Lucknow', type: 'Park', coordinates: { lat: 26.8730, lng: 80.9975 }, timeRequired: 1.5, openingTime: '07:00', closingTime: '21:00', bestTimeOfDay: 'evening', rating: 4.4, tags: ['park', 'architecture', 'modern'], priceTier: 'free' },
  // MATHURA
  { _id: 'krishna_janmabhoomi', name: 'Krishna Janmabhoomi', cityName: 'Mathura', type: 'Religious', coordinates: { lat: 27.5046, lng: 77.6735 }, timeRequired: 1.5, openingTime: '05:00', closingTime: '21:00', bestTimeOfDay: 'morning', rating: 4.8, tags: ['religious', 'pilgrimage', 'krishna'], priceTier: 'free' },
  { _id: 'dwarkadhish_mathura', name: 'Dwarkadhish Temple', cityName: 'Mathura', type: 'Religious', coordinates: { lat: 27.5047, lng: 77.6739 }, timeRequired: 1, openingTime: '06:30', closingTime: '21:00', bestTimeOfDay: 'morning', rating: 4.6, tags: ['religious', 'heritage'], priceTier: 'free' },
  { _id: 'mathura_museum', name: 'Government Museum Mathura', cityName: 'Mathura', type: 'Museum', coordinates: { lat: 27.5007, lng: 77.6703 }, timeRequired: 1.5, openingTime: '10:30', closingTime: '16:30', bestTimeOfDay: 'morning', rating: 4.3, tags: ['museum', 'history', 'sculpture'], priceTier: 'low' },
  { _id: 'vishram_ghat', name: 'Vishram Ghat', cityName: 'Mathura', type: 'Ghat', coordinates: { lat: 27.5047, lng: 77.6891 }, timeRequired: 1, openingTime: '04:00', closingTime: '22:00', bestTimeOfDay: 'evening', rating: 4.4, tags: ['ghat', 'spiritual', 'yamuna'], priceTier: 'free' },
  { _id: 'kusum_sarovar', name: 'Kusum Sarovar', cityName: 'Mathura', type: 'Historical', coordinates: { lat: 27.5850, lng: 77.6600 }, timeRequired: 1, openingTime: '06:00', closingTime: '18:00', bestTimeOfDay: 'morning', rating: 4.2, tags: ['heritage', 'peaceful', 'architecture'], priceTier: 'free' },
  // BHOPAL
  { _id: 'upper_lake', name: 'Upper Lake (Bhojtal)', cityName: 'Bhopal', type: 'Nature', coordinates: { lat: 23.2393, lng: 77.3550 }, timeRequired: 1.5, openingTime: '06:00', closingTime: '20:00', bestTimeOfDay: 'evening', rating: 4.5, tags: ['nature', 'lake', 'boating'], priceTier: 'low' },
  { _id: 'sanchi_stupa', name: 'Sanchi Stupa', cityName: 'Bhopal', type: 'Historical', coordinates: { lat: 23.4793, lng: 77.7399 }, timeRequired: 3, openingTime: '06:30', closingTime: '17:30', bestTimeOfDay: 'morning', rating: 4.8, tags: ['UNESCO', 'buddhist', 'heritage'], priceTier: 'low' },
  { _id: 'bhimbetka', name: 'Bhimbetka Rock Shelters', cityName: 'Bhopal', type: 'Historical', coordinates: { lat: 22.9375, lng: 77.6116 }, timeRequired: 2.5, openingTime: '07:00', closingTime: '17:00', bestTimeOfDay: 'morning', rating: 4.7, tags: ['UNESCO', 'cave-art', 'prehistoric'], priceTier: 'low' },
  { _id: 'tribal_museum_bhopal', name: 'Tribal Museum', cityName: 'Bhopal', type: 'Museum', coordinates: { lat: 23.2369, lng: 77.4127 }, timeRequired: 1.5, openingTime: '10:00', closingTime: '18:00', bestTimeOfDay: 'afternoon', rating: 4.4, tags: ['museum', 'tribal', 'culture'], priceTier: 'low' },
  { _id: 'taj_ul_masjid', name: 'Taj-ul-Masajid', cityName: 'Bhopal', type: 'Religious', coordinates: { lat: 23.2674, lng: 77.4088 }, timeRequired: 1, openingTime: '05:00', closingTime: '21:00', bestTimeOfDay: 'morning', rating: 4.5, tags: ['religious', 'architecture', 'mosque'], priceTier: 'free' },
  // KHAJURAHO
  { _id: 'western_temples', name: 'Western Group of Temples', cityName: 'Khajuraho', type: 'Temple', coordinates: { lat: 24.8521, lng: 79.9195 }, timeRequired: 3, openingTime: '06:00', closingTime: '18:00', bestTimeOfDay: 'morning', rating: 4.9, tags: ['UNESCO', 'temple', 'sculpture'], priceTier: 'medium' },
  { _id: 'eastern_temples', name: 'Eastern Group of Temples', cityName: 'Khajuraho', type: 'Temple', coordinates: { lat: 24.8493, lng: 79.9349 }, timeRequired: 2, openingTime: '06:00', closingTime: '18:00', bestTimeOfDay: 'morning', rating: 4.6, tags: ['temple', 'jain', 'sculpture'], priceTier: 'free' },
  { _id: 'southern_temples', name: 'Southern Group of Temples', cityName: 'Khajuraho', type: 'Temple', coordinates: { lat: 24.8386, lng: 79.9218 }, timeRequired: 1.5, openingTime: '06:00', closingTime: '18:00', bestTimeOfDay: 'afternoon', rating: 4.3, tags: ['temple', 'heritage'], priceTier: 'free' },
  { _id: 'kandariya_mahadeva', name: 'Kandariya Mahadeva Temple', cityName: 'Khajuraho', type: 'Temple', coordinates: { lat: 24.8518, lng: 79.9194 }, timeRequired: 1, openingTime: '06:00', closingTime: '18:00', bestTimeOfDay: 'morning', rating: 4.8, tags: ['temple', 'masterpiece', 'shiva'], priceTier: 'medium' },
  { _id: 'khajuraho_museum', name: 'Archaeological Museum', cityName: 'Khajuraho', type: 'Museum', coordinates: { lat: 24.8513, lng: 79.9209 }, timeRequired: 1.5, openingTime: '10:00', closingTime: '17:00', bestTimeOfDay: 'afternoon', rating: 4.2, tags: ['museum', 'archaeology', 'sculpture'], priceTier: 'low' },
  // UJJAIN
  { _id: 'mahakaleshwar', name: 'Mahakaleshwar Temple', cityName: 'Ujjain', type: 'Religious', coordinates: { lat: 23.1828, lng: 75.7683 }, timeRequired: 2, openingTime: '04:00', closingTime: '23:00', bestTimeOfDay: 'morning', rating: 4.9, tags: ['jyotirlinga', 'religious', 'pilgrimage'], priceTier: 'free' },
  { _id: 'ram_ghat_ujjain', name: 'Ram Ghat', cityName: 'Ujjain', type: 'Ghat', coordinates: { lat: 23.1893, lng: 75.7587 }, timeRequired: 1, openingTime: '05:00', closingTime: '21:00', bestTimeOfDay: 'evening', rating: 4.5, tags: ['ghat', 'spiritual', 'kumbh'], priceTier: 'free' },
  { _id: 'kal_bhairav_ujjain', name: 'Kal Bhairav Temple', cityName: 'Ujjain', type: 'Religious', coordinates: { lat: 23.1840, lng: 75.7621 }, timeRequired: 0.5, openingTime: '05:00', closingTime: '22:00', bestTimeOfDay: 'morning', rating: 4.3, tags: ['religious', 'unique', 'tantric'], priceTier: 'free' },
  { _id: 'vedha_shala', name: 'Vedha Shala (Observatory)', cityName: 'Ujjain', type: 'Historical', coordinates: { lat: 23.1796, lng: 75.7651 }, timeRequired: 1, openingTime: '10:00', closingTime: '17:00', bestTimeOfDay: 'morning', rating: 4.2, tags: ['science', 'history', 'astronomy'], priceTier: 'low' },
  { _id: 'mangalnath_temple', name: 'Mangalnath Temple', cityName: 'Ujjain', type: 'Religious', coordinates: { lat: 23.1960, lng: 75.7508 }, timeRequired: 0.5, openingTime: '05:00', closingTime: '20:00', bestTimeOfDay: 'morning', rating: 4.1, tags: ['religious', 'mars', 'astrology'], priceTier: 'free' },
  // ORCHHA
  { _id: 'orchha_fort', name: 'Orchha Fort Complex', cityName: 'Orchha', type: 'Fort', coordinates: { lat: 25.3519, lng: 78.6419 }, timeRequired: 3, openingTime: '08:00', closingTime: '18:00', bestTimeOfDay: 'morning', rating: 4.7, tags: ['fort', 'bundela', 'heritage'], priceTier: 'medium' },
  { _id: 'raja_mahal', name: 'Raja Mahal', cityName: 'Orchha', type: 'Palace', coordinates: { lat: 25.3524, lng: 78.6405 }, timeRequired: 1.5, openingTime: '08:00', closingTime: '18:00', bestTimeOfDay: 'morning', rating: 4.5, tags: ['palace', 'murals', 'heritage'], priceTier: 'medium' },
  { _id: 'jahangir_mahal', name: 'Jahangir Mahal', cityName: 'Orchha', type: 'Palace', coordinates: { lat: 25.3515, lng: 78.6430 }, timeRequired: 1.5, openingTime: '08:00', closingTime: '18:00', bestTimeOfDay: 'morning', rating: 4.6, tags: ['palace', 'mughal', 'architecture'], priceTier: 'medium' },
  { _id: 'chaturbhuj_temple', name: 'Chaturbhuj Temple', cityName: 'Orchha', type: 'Temple', coordinates: { lat: 25.3495, lng: 78.6415 }, timeRequired: 1, openingTime: '06:00', closingTime: '18:00', bestTimeOfDay: 'morning', rating: 4.4, tags: ['temple', 'architecture', 'views'], priceTier: 'free' },
  { _id: 'orchha_cenotaphs', name: 'Royal Cenotaphs (Chhatris)', cityName: 'Orchha', type: 'Historical', coordinates: { lat: 25.3502, lng: 78.6388 }, timeRequired: 1, openingTime: '06:00', closingTime: '18:00', bestTimeOfDay: 'evening', rating: 4.5, tags: ['heritage', 'sunset', 'architecture'], priceTier: 'free' },
  // KOCHI
  { _id: 'fort_kochi', name: 'Fort Kochi', cityName: 'Kochi', type: 'Historical', coordinates: { lat: 9.9639, lng: 76.2425 }, timeRequired: 3, openingTime: '00:00', closingTime: '23:59', bestTimeOfDay: 'morning', rating: 4.6, tags: ['colonial', 'heritage', 'walking'], priceTier: 'free' },
  { _id: 'chinese_fishing_nets', name: 'Chinese Fishing Nets', cityName: 'Kochi', type: 'Landmark', coordinates: { lat: 9.9674, lng: 76.2377 }, timeRequired: 1, openingTime: '00:00', closingTime: '23:59', bestTimeOfDay: 'evening', rating: 4.5, tags: ['iconic', 'sunset', 'photography'], priceTier: 'free' },
  { _id: 'mattancherry_palace', name: 'Mattancherry Palace', cityName: 'Kochi', type: 'Museum', coordinates: { lat: 9.9581, lng: 76.2594 }, timeRequired: 1.5, openingTime: '10:00', closingTime: '17:00', bestTimeOfDay: 'morning', rating: 4.4, tags: ['museum', 'heritage', 'murals'], priceTier: 'low' },
  { _id: 'jewish_synagogue', name: 'Paradesi Synagogue', cityName: 'Kochi', type: 'Historical', coordinates: { lat: 9.9575, lng: 76.2601 }, timeRequired: 0.5, openingTime: '10:00', closingTime: '17:00', bestTimeOfDay: 'morning', rating: 4.3, tags: ['heritage', 'religious', 'colonial'], priceTier: 'low' },
  { _id: 'marine_drive_kochi', name: 'Marine Drive', cityName: 'Kochi', type: 'Promenade', coordinates: { lat: 9.9735, lng: 76.2799 }, timeRequired: 1.5, openingTime: '00:00', closingTime: '23:59', bestTimeOfDay: 'evening', rating: 4.4, tags: ['waterfront', 'walking', 'sunset'], priceTier: 'free' }
];

export const HOTELS = [
  // JAIPUR
  {
    _id: 'hotel_pearl_palace',
    name: 'Hotel Pearl Palace',
    cityName: 'Jaipur',
    stateCode: 'RAJASTHAN',
    coordinates: { lat: 26.9060, lng: 75.7993 },
    tier: 'budget' as const,
    pricePerNight: 1200,
    rating: 4.2,
    amenities: ['WiFi', 'AC', 'Restaurant', 'Rooftop Cafe', '24h Front Desk'],
    imageUrl: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=400&h=300&fit=crop',
    contactPhone: '+91-141-2373700',
    description: 'A beloved budget gem in the Pink City with a famous rooftop restaurant and warm hospitality.'
  },
  {
    _id: 'hotel_narain_niwas',
    name: 'Hotel Narain Niwas Palace',
    cityName: 'Jaipur',
    stateCode: 'RAJASTHAN',
    coordinates: { lat: 26.8986, lng: 75.8060 },
    tier: 'standard' as const,
    pricePerNight: 3500,
    rating: 4.5,
    amenities: ['WiFi', 'AC', 'Pool', 'Restaurant', 'Garden', 'Heritage Property', 'Parking'],
    imageUrl: 'https://images.unsplash.com/photo-1582719508461-905c673771fd?w=400&h=300&fit=crop',
    contactPhone: '+91-141-2561291',
    description: 'A heritage palace hotel set in lush gardens, offering an authentic Rajasthani royal experience.'
  },
  {
    _id: 'rambagh_palace',
    name: 'Rambagh Palace',
    cityName: 'Jaipur',
    stateCode: 'RAJASTHAN',
    coordinates: { lat: 26.8953, lng: 75.8076 },
    tier: 'premium' as const,
    pricePerNight: 15000,
    rating: 4.9,
    amenities: ['WiFi', 'AC', 'Pool', 'Spa', 'Fine Dining', 'Butler Service', 'Golf', 'Heritage Property'],
    imageUrl: 'https://images.unsplash.com/photo-1615460549969-36fa19521a4f?w=400&h=300&fit=crop',
    contactPhone: '+91-141-2211919',
    bookingUrl: 'https://www.tajhotels.com/rambagh-palace',
    description: 'The jewel of Jaipur — a former royal residence turned ultra-luxury Taj hotel with impeccable grandeur.'
  },

  // UDAIPUR
  {
    _id: 'hotel_jagat_niwas',
    name: 'Jagat Niwas Palace',
    cityName: 'Udaipur',
    stateCode: 'RAJASTHAN',
    coordinates: { lat: 24.5764, lng: 73.6810 },
    tier: 'budget' as const,
    pricePerNight: 1500,
    rating: 4.3,
    amenities: ['WiFi', 'AC', 'Lake View', 'Restaurant', 'Rooftop Terrace'],
    imageUrl: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=400&h=300&fit=crop',
    contactPhone: '+91-294-2420133',
    description: 'A charming haveli on the shores of Lake Pichola with stunning views and heritage character.'
  },
  {
    _id: 'hotel_fateh_prakash',
    name: 'Fateh Prakash Palace',
    cityName: 'Udaipur',
    stateCode: 'RAJASTHAN',
    coordinates: { lat: 24.5750, lng: 73.6841 },
    tier: 'standard' as const,
    pricePerNight: 4000,
    rating: 4.6,
    amenities: ['WiFi', 'AC', 'Pool', 'Lake View', 'Restaurant', 'Spa', 'Heritage Property'],
    imageUrl: 'https://images.unsplash.com/photo-1582719508461-905c673771fd?w=400&h=300&fit=crop',
    contactPhone: '+91-294-2528016',
    description: 'A grand palace hotel within the City Palace complex, offering regal lakeside luxury.'
  },
  {
    _id: 'oberoi_udaivilas',
    name: 'The Oberoi Udaivilas',
    cityName: 'Udaipur',
    stateCode: 'RAJASTHAN',
    coordinates: { lat: 24.5680, lng: 73.6700 },
    tier: 'premium' as const,
    pricePerNight: 18000,
    rating: 4.9,
    amenities: ['WiFi', 'AC', 'Pool', 'Spa', 'Fine Dining', 'Butler Service', 'Lake View', 'Boat Rides'],
    imageUrl: 'https://images.unsplash.com/photo-1615460549969-36fa19521a4f?w=400&h=300&fit=crop',
    contactPhone: '+91-294-2433300',
    bookingUrl: 'https://www.oberoihotels.com/udaivilas',
    description: 'Consistently rated among the world\'s best hotels, set on the banks of Lake Pichola with private pools.'
  },

  // JODHPUR
  {
    _id: 'hotel_haveli_inn',
    name: 'Haveli Inn Pal',
    cityName: 'Jodhpur',
    stateCode: 'RAJASTHAN',
    coordinates: { lat: 26.2960, lng: 73.0250 },
    tier: 'budget' as const,
    pricePerNight: 1000,
    rating: 4.1,
    amenities: ['WiFi', 'AC', 'Restaurant', 'Fort View', '24h Front Desk'],
    imageUrl: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=400&h=300&fit=crop',
    contactPhone: '+91-291-3293328',
    description: 'A traditional haveli in the Blue City with fort views and authentic Rajasthani meals.'
  },
  {
    _id: 'hotel_vivanta_jodhpur',
    name: 'Vivanta Jodhpur',
    cityName: 'Jodhpur',
    stateCode: 'RAJASTHAN',
    coordinates: { lat: 26.2650, lng: 73.0380 },
    tier: 'standard' as const,
    pricePerNight: 3800,
    rating: 4.5,
    amenities: ['WiFi', 'AC', 'Pool', 'Spa', 'Restaurant', 'Gym', 'Business Center'],
    imageUrl: 'https://images.unsplash.com/photo-1582719508461-905c673771fd?w=400&h=300&fit=crop',
    contactPhone: '+91-291-2510101',
    description: 'A modern luxury hotel by Taj with panoramic views of the Mehrangarh Fort and blue cityscape.'
  },
  {
    _id: 'umaid_bhawan_hotel',
    name: 'Umaid Bhawan Palace Hotel',
    cityName: 'Jodhpur',
    stateCode: 'RAJASTHAN',
    coordinates: { lat: 26.2808, lng: 73.0474 },
    tier: 'premium' as const,
    pricePerNight: 20000,
    rating: 4.9,
    amenities: ['WiFi', 'AC', 'Pool', 'Spa', 'Fine Dining', 'Butler Service', 'Museum', 'Garden', 'Heritage Property'],
    imageUrl: 'https://images.unsplash.com/photo-1615460549969-36fa19521a4f?w=400&h=300&fit=crop',
    contactPhone: '+91-291-2510101',
    bookingUrl: 'https://www.tajhotels.com/umaid-bhawan-palace',
    description: 'One of the world\'s largest private residences, now a Taj Palace hotel with Art Deco interiors.'
  },

  // JAISALMER
  {
    _id: 'hotel_fifu',
    name: 'Hotel Fifu',
    cityName: 'Jaisalmer',
    stateCode: 'RAJASTHAN',
    coordinates: { lat: 26.9130, lng: 70.9100 },
    tier: 'budget' as const,
    pricePerNight: 800,
    rating: 4.0,
    amenities: ['WiFi', 'AC', 'Restaurant', 'Fort View', 'Desert Tours'],
    imageUrl: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=400&h=300&fit=crop',
    contactPhone: '+91-2992-252382',
    description: 'A cozy budget hotel near the golden fort with desert safari arrangements and rooftop dining.'
  },
  {
    _id: 'hotel_suryagarh',
    name: 'Suryagarh',
    cityName: 'Jaisalmer',
    stateCode: 'RAJASTHAN',
    coordinates: { lat: 26.8700, lng: 70.8900 },
    tier: 'standard' as const,
    pricePerNight: 4500,
    rating: 4.7,
    amenities: ['WiFi', 'AC', 'Pool', 'Spa', 'Restaurant', 'Desert Camp', 'Cultural Shows', 'Heritage Property'],
    imageUrl: 'https://images.unsplash.com/photo-1582719508461-905c673771fd?w=400&h=300&fit=crop',
    contactPhone: '+91-2992-269269',
    description: 'A stunning fortress hotel on the outskirts of Jaisalmer with curated desert experiences.'
  },
  {
    _id: 'hotel_serai',
    name: 'The Serai',
    cityName: 'Jaisalmer',
    stateCode: 'RAJASTHAN',
    coordinates: { lat: 26.8500, lng: 70.8700 },
    tier: 'premium' as const,
    pricePerNight: 12000,
    rating: 4.8,
    amenities: ['WiFi', 'AC', 'Pool', 'Spa', 'Fine Dining', 'Desert Camp', 'Stargazing', 'Private Tents'],
    imageUrl: 'https://images.unsplash.com/photo-1615460549969-36fa19521a4f?w=400&h=300&fit=crop',
    contactPhone: '+91-2992-269001',
    bookingUrl: 'https://www.theserai.in/jaisalmer',
    description: 'An ultra-luxury desert camp resort with private tented suites and stargazing from the Thar Desert.'
  },
  // AHMEDABAD
  { _id: 'hotel_house_of_mg', name: 'House of MG', cityName: 'Ahmedabad', stateCode: 'GUJARAT', coordinates: { lat: 23.0258, lng: 72.5714 }, tier: 'standard' as const, pricePerNight: 3500, rating: 4.6, amenities: ['WiFi', 'AC', 'Restaurant', 'Heritage', 'Pool'], description: 'A heritage hotel in the Old City with award-winning Gujarati dining.' },
  { _id: 'hotel_hyatt_ahmedabad', name: 'Hyatt Regency Ahmedabad', cityName: 'Ahmedabad', stateCode: 'GUJARAT', coordinates: { lat: 23.0300, lng: 72.5700 }, tier: 'premium' as const, pricePerNight: 6500, rating: 4.7, amenities: ['WiFi', 'AC', 'Pool', 'Spa', 'Gym', 'Restaurant'], description: 'Modern luxury hotel with skyline views and world-class amenities.' },
  { _id: 'hotel_lemon_tree_ahd', name: 'Lemon Tree Premier', cityName: 'Ahmedabad', stateCode: 'GUJARAT', coordinates: { lat: 23.0350, lng: 72.5650 }, tier: 'budget' as const, pricePerNight: 1800, rating: 4.1, amenities: ['WiFi', 'AC', 'Restaurant'], description: 'Cheerful budget hotel with reliable service near SG Highway.' },
  // AGRA
  { _id: 'hotel_oberoi_amarvilas', name: 'The Oberoi Amarvilas', cityName: 'Agra', stateCode: 'UTTAR_PRADESH', coordinates: { lat: 27.1720, lng: 78.0400 }, tier: 'premium' as const, pricePerNight: 25000, rating: 4.9, amenities: ['WiFi', 'AC', 'Pool', 'Spa', 'Taj View', 'Fine Dining', 'Butler'], description: 'Every room offers uninterrupted Taj Mahal views — the ultimate luxury.' },
  { _id: 'hotel_crystal_sarovar', name: 'Crystal Sarovar Premiere', cityName: 'Agra', stateCode: 'UTTAR_PRADESH', coordinates: { lat: 27.1800, lng: 78.0200 }, tier: 'standard' as const, pricePerNight: 3200, rating: 4.3, amenities: ['WiFi', 'AC', 'Pool', 'Restaurant'], description: 'Comfortable mid-range hotel close to Agra Fort with rooftop dining.' },
  { _id: 'hotel_zostel_agra', name: 'Zostel Agra', cityName: 'Agra', stateCode: 'UTTAR_PRADESH', coordinates: { lat: 27.1750, lng: 78.0450 }, tier: 'budget' as const, pricePerNight: 600, rating: 4.0, amenities: ['WiFi', 'Common Kitchen', 'Rooftop'], description: 'Backpacker hostel with Taj views from the rooftop and vibrant community.' },
  // VARANASI
  { _id: 'hotel_taj_nadesar', name: 'Taj Nadesar Palace', cityName: 'Varanasi', stateCode: 'UTTAR_PRADESH', coordinates: { lat: 25.3100, lng: 83.0000 }, tier: 'premium' as const, pricePerNight: 18000, rating: 4.8, amenities: ['WiFi', 'AC', 'Pool', 'Spa', 'Garden', 'Heritage'], description: 'A restored palace hotel set in jasmine-scented gardens.' },
  { _id: 'hotel_brijrama', name: 'BrijRama Palace', cityName: 'Varanasi', stateCode: 'UTTAR_PRADESH', coordinates: { lat: 25.3050, lng: 83.0100 }, tier: 'standard' as const, pricePerNight: 5500, rating: 4.6, amenities: ['WiFi', 'AC', 'Restaurant', 'Ghat View', 'Heritage'], description: 'Heritage ghat-side palace with Ganga views and boat rides.' },
  { _id: 'hotel_stops_varanasi', name: 'Stops Hostel Varanasi', cityName: 'Varanasi', stateCode: 'UTTAR_PRADESH', coordinates: { lat: 25.3150, lng: 83.0050 }, tier: 'budget' as const, pricePerNight: 500, rating: 4.1, amenities: ['WiFi', 'Common Area', 'Cafe'], description: 'Clean budget stay near Assi Ghat with rooftop cafe.' },
  // LUCKNOW
  { _id: 'hotel_taj_lucknow', name: 'Taj Mahal Lucknow', cityName: 'Lucknow', stateCode: 'UTTAR_PRADESH', coordinates: { lat: 26.8500, lng: 80.9500 }, tier: 'premium' as const, pricePerNight: 8000, rating: 4.7, amenities: ['WiFi', 'AC', 'Pool', 'Spa', 'Restaurant', 'Gym'], description: 'Grand luxury hotel in the heart of Lucknow with Awadhi fine dining.' },
  { _id: 'hotel_gomti_lucknow', name: 'Hotel Gomti', cityName: 'Lucknow', stateCode: 'UTTAR_PRADESH', coordinates: { lat: 26.8550, lng: 80.9400 }, tier: 'budget' as const, pricePerNight: 1200, rating: 3.9, amenities: ['WiFi', 'AC', 'Restaurant'], description: 'No-frills budget hotel near Hazratganj market.' },
  // BHOPAL
  { _id: 'hotel_jehan_numa', name: 'Jehan Numa Palace', cityName: 'Bhopal', stateCode: 'MADHYA_PRADESH', coordinates: { lat: 23.2400, lng: 77.4000 }, tier: 'premium' as const, pricePerNight: 7500, rating: 4.6, amenities: ['WiFi', 'AC', 'Pool', 'Spa', 'Heritage', 'Restaurant'], description: 'A 19th-century palace hotel with lush gardens and equestrian charm.' },
  { _id: 'hotel_noor_us_sabah', name: 'Noor-Us-Sabah Palace', cityName: 'Bhopal', stateCode: 'MADHYA_PRADESH', coordinates: { lat: 23.2350, lng: 77.3900 }, tier: 'standard' as const, pricePerNight: 3800, rating: 4.4, amenities: ['WiFi', 'AC', 'Pool', 'Restaurant', 'Lake View'], description: 'Heritage hotel overlooking Upper Lake with Nawabi architecture.' },
  { _id: 'hotel_zostel_bhopal', name: 'Zostel Bhopal', cityName: 'Bhopal', stateCode: 'MADHYA_PRADESH', coordinates: { lat: 23.2500, lng: 77.4100 }, tier: 'budget' as const, pricePerNight: 550, rating: 4.0, amenities: ['WiFi', 'Common Area', 'Kitchen'], description: 'Backpacker-friendly hostel near the old city.' },
  // KHAJURAHO
  { _id: 'hotel_lalit_khajuraho', name: 'The Lalit Temple View', cityName: 'Khajuraho', stateCode: 'MADHYA_PRADESH', coordinates: { lat: 24.8400, lng: 79.9200 }, tier: 'premium' as const, pricePerNight: 6000, rating: 4.5, amenities: ['WiFi', 'AC', 'Pool', 'Spa', 'Restaurant', 'Temple View'], description: 'Resort-style hotel with views of the Western Group of Temples.' },
  { _id: 'hotel_chandela_khajuraho', name: 'Hotel Chandela', cityName: 'Khajuraho', stateCode: 'MADHYA_PRADESH', coordinates: { lat: 24.8450, lng: 79.9250 }, tier: 'standard' as const, pricePerNight: 2800, rating: 4.2, amenities: ['WiFi', 'AC', 'Pool', 'Restaurant'], description: 'Comfortable hotel with large pool and proximity to temple sites.' },
  // KOCHI
  { _id: 'hotel_brunton_kochi', name: 'Brunton Boatyard', cityName: 'Kochi', stateCode: 'KERALA', coordinates: { lat: 9.9660, lng: 76.2400 }, tier: 'premium' as const, pricePerNight: 9000, rating: 4.7, amenities: ['WiFi', 'AC', 'Pool', 'Sea View', 'Heritage', 'Restaurant'], description: 'A CGH Earth heritage hotel on the waterfront of Fort Kochi.' },
  { _id: 'hotel_old_harbour', name: 'Old Harbour Hotel', cityName: 'Kochi', stateCode: 'KERALA', coordinates: { lat: 9.9640, lng: 76.2430 }, tier: 'standard' as const, pricePerNight: 4000, rating: 4.5, amenities: ['WiFi', 'AC', 'Pool', 'Restaurant', 'Heritage'], description: 'Boutique heritage hotel with Dutch-colonial charm in Fort Kochi.' },
  { _id: 'hotel_zostel_kochi', name: 'Zostel Kochi', cityName: 'Kochi', stateCode: 'KERALA', coordinates: { lat: 9.9650, lng: 76.2420 }, tier: 'budget' as const, pricePerNight: 500, rating: 4.0, amenities: ['WiFi', 'Common Area', 'Cafe'], description: 'Colorful hostel in Fort Kochi with bike rentals and community events.' }
];

export const RESTAURANTS = [
  // JAIPUR (6)
  {
    _id: 'lmb_jaipur',
    name: 'LMB (Laxmi Mishthan Bhandar)',
    cityName: 'Jaipur',
    cuisine: ['Rajasthani', 'North Indian', 'Sweets'],
    type: 'casual' as const,
    priceRange: 'budget' as const,
    averageCost: 250,
    rating: 4.4,
    mustTry: ['Ghevar', 'Dal Baati Churma', 'Rajasthani Thali'],
    coordinates: { lat: 26.9220, lng: 75.8235 },
    openingTime: '08:00',
    closingTime: '23:00',
    vegetarian: true,
    description: 'Iconic 1727-era sweet shop and restaurant in Johari Bazaar, legendary for Ghevar and traditional Rajasthani thali.'
  },
  {
    _id: 'rawat_jaipur',
    name: 'Rawat Mishthan Bhandar',
    cityName: 'Jaipur',
    cuisine: ['Street Food', 'Sweets', 'Rajasthani'],
    type: 'street-food' as const,
    priceRange: 'budget' as const,
    averageCost: 120,
    rating: 4.3,
    mustTry: ['Pyaz Kachori', 'Mirchi Vada', 'Mawa Kachori'],
    coordinates: { lat: 26.9050, lng: 75.7920 },
    openingTime: '06:30',
    closingTime: '22:30',
    vegetarian: true,
    description: 'The most famous kachori spot in Jaipur — the pyaz kachori is a must-eat for every visitor.'
  },
  {
    _id: 'handi_jaipur',
    name: 'Handi Restaurant',
    cityName: 'Jaipur',
    cuisine: ['Mughlai', 'Rajasthani', 'Non-Veg'],
    type: 'casual' as const,
    priceRange: 'moderate' as const,
    averageCost: 500,
    rating: 4.2,
    mustTry: ['Laal Maas', 'Handi Chicken', 'Butter Naan'],
    coordinates: { lat: 26.9170, lng: 75.8070 },
    openingTime: '11:00',
    closingTime: '23:00',
    vegetarian: false,
    description: 'Popular for its fiery Laal Maas and slow-cooked handi preparations, located near MI Road.'
  },
  {
    _id: 'tapri_jaipur',
    name: 'Tapri Central',
    cityName: 'Jaipur',
    cuisine: ['Cafe', 'Continental', 'Indian Fusion'],
    type: 'cafe' as const,
    priceRange: 'moderate' as const,
    averageCost: 350,
    rating: 4.5,
    mustTry: ['Kulhad Chai', 'Maggi', 'Bun Maska'],
    coordinates: { lat: 26.9050, lng: 75.8010 },
    openingTime: '07:00',
    closingTime: '23:30',
    vegetarian: true,
    description: 'Jaipur\'s beloved rooftop chai cafe with stunning Nahargarh Fort views and quirky ambiance.'
  },
  {
    _id: 'spice_court_jaipur',
    name: 'Spice Court',
    cityName: 'Jaipur',
    cuisine: ['Rajasthani', 'North Indian', 'Mughlai'],
    type: 'casual' as const,
    priceRange: 'moderate' as const,
    averageCost: 600,
    rating: 4.4,
    mustTry: ['Ker Sangri', 'Gatte Ki Sabzi', 'Jungli Maas'],
    coordinates: { lat: 26.9100, lng: 75.7900 },
    openingTime: '11:00',
    closingTime: '23:00',
    vegetarian: false,
    description: 'A go-to spot for authentic Rajasthani cuisine in a cozy courtyard setting near C-Scheme.'
  },
  {
    _id: '1135ad_jaipur',
    name: '1135 AD',
    cityName: 'Jaipur',
    cuisine: ['Royal Rajasthani', 'Fine Dining', 'Indian'],
    type: 'fine-dining' as const,
    priceRange: 'expensive' as const,
    averageCost: 2500,
    rating: 4.7,
    mustTry: ['Royal Thali', 'Safed Maas', 'Paneer Lababdar'],
    coordinates: { lat: 26.9855, lng: 75.8513 },
    openingTime: '12:00',
    closingTime: '22:30',
    vegetarian: false,
    description: 'Fine dining inside Amber Fort — named after the year of its construction, with royal Rajput cuisine.'
  },

  // UDAIPUR (6)
  {
    _id: 'natraj_udaipur',
    name: 'Natraj Dining Hall',
    cityName: 'Udaipur',
    cuisine: ['Rajasthani', 'Gujarati', 'Thali'],
    type: 'dhaba' as const,
    priceRange: 'budget' as const,
    averageCost: 180,
    rating: 4.2,
    mustTry: ['Unlimited Thali', 'Dal Baati', 'Churma Ladoo'],
    coordinates: { lat: 24.5790, lng: 73.6850 },
    openingTime: '10:30',
    closingTime: '22:30',
    vegetarian: true,
    description: 'No-frills thali restaurant serving hearty unlimited Rajasthani-Gujarati meals at honest prices.'
  },
  {
    _id: 'savage_garden_udaipur',
    name: 'Savage Garden',
    cityName: 'Udaipur',
    cuisine: ['Continental', 'Italian', 'Indian Fusion'],
    type: 'cafe' as const,
    priceRange: 'moderate' as const,
    averageCost: 450,
    rating: 4.5,
    mustTry: ['Wood-fired Pizza', 'Hummus Platter', 'Fresh Juices'],
    coordinates: { lat: 24.5780, lng: 73.6830 },
    openingTime: '08:30',
    closingTime: '22:30',
    vegetarian: false,
    description: 'A leafy rooftop cafe near Chandpole with lake glimpses, known for global comfort food and cocktails.'
  },
  {
    _id: 'ambrai_udaipur',
    name: 'Ambrai',
    cityName: 'Udaipur',
    cuisine: ['Indian', 'Continental', 'Rajasthani'],
    type: 'fine-dining' as const,
    priceRange: 'expensive' as const,
    averageCost: 1800,
    rating: 4.8,
    mustTry: ['Lake Pichola View Dinner', 'Paneer Tikka', 'Laal Maas'],
    coordinates: { lat: 24.5760, lng: 73.6790 },
    openingTime: '12:30',
    closingTime: '22:30',
    vegetarian: false,
    description: 'Udaipur\'s most romantic dining spot — lakeside at Amet Haveli with City Palace lit up across the water.'
  },
  {
    _id: 'millets_of_mewar_udaipur',
    name: 'Millets of Mewar',
    cityName: 'Udaipur',
    cuisine: ['Healthy', 'Rajasthani', 'Organic'],
    type: 'casual' as const,
    priceRange: 'moderate' as const,
    averageCost: 400,
    rating: 4.4,
    mustTry: ['Bajra Roti', 'Millet Thali', 'Jowar Pizza'],
    coordinates: { lat: 24.5800, lng: 73.6820 },
    openingTime: '09:00',
    closingTime: '22:00',
    vegetarian: true,
    description: 'A unique farm-to-fork restaurant celebrating Rajasthan\'s millet heritage with creative dishes.'
  },
  {
    _id: 'jheel_cafe_udaipur',
    name: 'Jheel\'s Ginger Coffee Bar',
    cityName: 'Udaipur',
    cuisine: ['Cafe', 'Bakery', 'Continental'],
    type: 'cafe' as const,
    priceRange: 'budget' as const,
    averageCost: 200,
    rating: 4.3,
    mustTry: ['Filter Coffee', 'Banana Pancakes', 'Croissant'],
    coordinates: { lat: 24.5770, lng: 73.6840 },
    openingTime: '07:30',
    closingTime: '21:00',
    vegetarian: true,
    description: 'A cozy lakeside cafe perfect for a morning coffee with views of the ghats.'
  },
  {
    _id: 'upre_udaipur',
    name: 'Upré by 1559 AD',
    cityName: 'Udaipur',
    cuisine: ['Indian', 'Continental', 'Mediterranean'],
    type: 'fine-dining' as const,
    priceRange: 'expensive' as const,
    averageCost: 2000,
    rating: 4.6,
    mustTry: ['Grilled Lamb Chops', 'Risotto', 'Chef\'s Tasting Menu'],
    coordinates: { lat: 24.5755, lng: 73.6835 },
    openingTime: '19:00',
    closingTime: '23:00',
    vegetarian: false,
    description: 'Rooftop fine dining atop Lake Pichola Hotel with a curated multi-course menu and live music.'
  },

  // JODHPUR (6)
  {
    _id: 'mishrilal_jodhpur',
    name: 'Shri Mishrilal Hotel',
    cityName: 'Jodhpur',
    cuisine: ['Street Food', 'Sweets', 'Rajasthani'],
    type: 'street-food' as const,
    priceRange: 'budget' as const,
    averageCost: 80,
    rating: 4.5,
    mustTry: ['Makhania Lassi', 'Mirchi Vada', 'Samosa'],
    coordinates: { lat: 26.2975, lng: 73.0215 },
    openingTime: '07:00',
    closingTime: '21:00',
    vegetarian: true,
    description: 'Jodhpur\'s legendary street-side stall near the clock tower — the Makhania Lassi is unmissable.'
  },
  {
    _id: 'jhankar_jodhpur',
    name: 'Jhankar Choti Haveli',
    cityName: 'Jodhpur',
    cuisine: ['Rajasthani', 'North Indian'],
    type: 'casual' as const,
    priceRange: 'moderate' as const,
    averageCost: 450,
    rating: 4.3,
    mustTry: ['Rajasthani Thali', 'Ker Sangri', 'Bajra Roti'],
    coordinates: { lat: 26.2950, lng: 73.0200 },
    openingTime: '10:00',
    closingTime: '22:00',
    vegetarian: false,
    description: 'A heritage haveli restaurant serving authentic Marwari food with folk music performances.'
  },
  {
    _id: 'on_the_rocks_jodhpur',
    name: 'On The Rocks',
    cityName: 'Jodhpur',
    cuisine: ['Continental', 'Indian', 'BBQ'],
    type: 'casual' as const,
    priceRange: 'moderate' as const,
    averageCost: 600,
    rating: 4.4,
    mustTry: ['BBQ Platter', 'Butter Chicken', 'Sizzlers'],
    coordinates: { lat: 26.2700, lng: 73.0350 },
    openingTime: '11:00',
    closingTime: '23:00',
    vegetarian: false,
    description: 'Open-air garden restaurant with live grill counters and a lively vibe, popular with locals.'
  },
  {
    _id: 'indique_jodhpur',
    name: 'Indique',
    cityName: 'Jodhpur',
    cuisine: ['Indian', 'Rajasthani', 'Fine Dining'],
    type: 'fine-dining' as const,
    priceRange: 'expensive' as const,
    averageCost: 1500,
    rating: 4.6,
    mustTry: ['Mehrangarh View Dinner', 'Laal Maas', 'Paneer Handi'],
    coordinates: { lat: 26.2800, lng: 73.0300 },
    openingTime: '12:00',
    closingTime: '23:00',
    vegetarian: false,
    description: 'Rooftop fine dining with a jaw-dropping view of Mehrangarh Fort — arguably the best dinner view in Jodhpur.'
  },
  {
    _id: 'omelette_shop_jodhpur',
    name: 'Shahi Samosa & Omelette Shop',
    cityName: 'Jodhpur',
    cuisine: ['Street Food', 'Breakfast'],
    type: 'street-food' as const,
    priceRange: 'budget' as const,
    averageCost: 60,
    rating: 4.1,
    mustTry: ['Shahi Samosa', 'Masala Omelette', 'Bread Omelette'],
    coordinates: { lat: 26.2960, lng: 73.0230 },
    openingTime: '06:00',
    closingTime: '14:00',
    vegetarian: false,
    description: 'Early morning staple near Sardar Market — crispy samosas and fluffy omelettes since decades.'
  },
  {
    _id: 'stepwell_cafe_jodhpur',
    name: 'Stepwell Cafe',
    cityName: 'Jodhpur',
    cuisine: ['Cafe', 'Continental', 'Indian'],
    type: 'cafe' as const,
    priceRange: 'moderate' as const,
    averageCost: 350,
    rating: 4.6,
    mustTry: ['Cold Coffee', 'Avocado Toast', 'Shakshuka'],
    coordinates: { lat: 26.2940, lng: 73.0180 },
    openingTime: '08:00',
    closingTime: '22:00',
    vegetarian: true,
    description: 'A stunning cafe built around the restored Toorji Ka Jhalra stepwell — Instagram-famous and delicious.'
  },

  // JAISALMER (6)
  {
    _id: 'free_tibet_jaisalmer',
    name: 'Free Tibet',
    cityName: 'Jaisalmer',
    cuisine: ['Tibetan', 'Chinese', 'Indian'],
    type: 'casual' as const,
    priceRange: 'budget' as const,
    averageCost: 150,
    rating: 4.2,
    mustTry: ['Momos', 'Thukpa', 'Veg Fried Rice'],
    coordinates: { lat: 26.9140, lng: 70.9130 },
    openingTime: '09:00',
    closingTime: '22:00',
    vegetarian: false,
    description: 'A backpacker favorite inside the living fort, serving comforting Tibetan food and chai.'
  },
  {
    _id: 'trio_jaisalmer',
    name: 'Trio',
    cityName: 'Jaisalmer',
    cuisine: ['Indian', 'Continental', 'Cafe'],
    type: 'cafe' as const,
    priceRange: 'moderate' as const,
    averageCost: 400,
    rating: 4.5,
    mustTry: ['Pasta', 'Fort View Breakfast', 'Fresh Lime Soda'],
    coordinates: { lat: 26.9130, lng: 70.9110 },
    openingTime: '07:30',
    closingTime: '23:00',
    vegetarian: false,
    description: 'Rooftop cafe with panoramic fort views, a perfect sunrise breakfast spot with global menu.'
  },
  {
    _id: 'first_gate_jaisalmer',
    name: '1st Gate Home Fusion',
    cityName: 'Jaisalmer',
    cuisine: ['Fusion', 'Italian', 'Indian'],
    type: 'casual' as const,
    priceRange: 'moderate' as const,
    averageCost: 500,
    rating: 4.6,
    mustTry: ['Truffle Pasta', 'Tandoori Paneer', 'Brownie Sundae'],
    coordinates: { lat: 26.9120, lng: 70.9120 },
    openingTime: '10:00',
    closingTime: '22:30',
    vegetarian: false,
    description: 'Creative fusion cuisine in a beautifully restored haveli near the first gate of Jaisalmer Fort.'
  },
  {
    _id: 'bhang_shop_jaisalmer',
    name: 'The Bhang Shop',
    cityName: 'Jaisalmer',
    cuisine: ['Street Food', 'Drinks', 'Rajasthani'],
    type: 'street-food' as const,
    priceRange: 'budget' as const,
    averageCost: 100,
    rating: 4.0,
    mustTry: ['Bhang Lassi', 'Pyaz Kachori', 'Chai'],
    coordinates: { lat: 26.9150, lng: 70.9140 },
    openingTime: '08:00',
    closingTime: '20:00',
    vegetarian: true,
    description: 'A quirky government-authorized shop near the fort — famous for its legendary bhang lassi.'
  },
  {
    _id: 'suryagarh_dining_jaisalmer',
    name: 'Nosh at Suryagarh',
    cityName: 'Jaisalmer',
    cuisine: ['Rajasthani', 'Continental', 'Fine Dining'],
    type: 'fine-dining' as const,
    priceRange: 'expensive' as const,
    averageCost: 2000,
    rating: 4.7,
    mustTry: ['Desert Tasting Menu', 'Laal Maas', 'Ker Sangri'],
    coordinates: { lat: 26.8700, lng: 70.8900 },
    openingTime: '12:30',
    closingTime: '22:30',
    vegetarian: false,
    description: 'Fine dining at Suryagarh hotel with curated Rajasthani and continental tasting menus under desert stars.'
  },
  {
    _id: 'monica_jaisalmer',
    name: 'Monica Restaurant',
    cityName: 'Jaisalmer',
    cuisine: ['Rajasthani', 'North Indian', 'Chinese'],
    type: 'dhaba' as const,
    priceRange: 'budget' as const,
    averageCost: 180,
    rating: 4.1,
    mustTry: ['Dal Baati Churma', 'Paneer Butter Masala', 'Roti'],
    coordinates: { lat: 26.9135, lng: 70.9125 },
    openingTime: '09:00',
    closingTime: '22:00',
    vegetarian: false,
    description: 'Reliable dhaba-style restaurant inside the fort walls with generous portions and homey flavors.'
  },
  // AHMEDABAD
  { _id: 'manek_chowk_ahd', name: 'Manek Chowk Night Market', cityName: 'Ahmedabad', cuisine: ['Street Food', 'Gujarati'], type: 'street-food' as const, priceRange: 'budget' as const, averageCost: 100, rating: 4.5, mustTry: ['Khaman', 'Dabeli', 'Kulfi Falooda'], coordinates: { lat: 23.0258, lng: 72.5793 }, openingTime: '19:00', closingTime: '01:00', vegetarian: true, description: 'Ahmedabad\'s legendary night street-food market in the Old City.' },
  { _id: 'agashiye_ahd', name: 'Agashiye', cityName: 'Ahmedabad', cuisine: ['Gujarati', 'Thali'], type: 'fine-dining' as const, priceRange: 'expensive' as const, averageCost: 1200, rating: 4.8, mustTry: ['Gujarati Thali', 'Undhiyu', 'Shrikhand'], coordinates: { lat: 23.0260, lng: 72.5720 }, openingTime: '11:00', closingTime: '22:30', vegetarian: true, description: 'Award-winning rooftop restaurant at House of MG serving traditional Gujarati thali.' },
  { _id: 'swati_snacks_ahd', name: 'Swati Snacks', cityName: 'Ahmedabad', cuisine: ['Gujarati', 'Snacks'], type: 'casual' as const, priceRange: 'moderate' as const, averageCost: 300, rating: 4.6, mustTry: ['Panki', 'Sev Usal', 'Handvo'], coordinates: { lat: 23.0300, lng: 72.5650 }, openingTime: '11:00', closingTime: '22:00', vegetarian: true, description: 'Iconic vegetarian snack house with innovative Gujarati street food.' },
  // AGRA
  { _id: 'peshawri_agra', name: 'Peshawri (ITC Mughal)', cityName: 'Agra', cuisine: ['North Indian', 'Mughlai', 'Tandoor'], type: 'fine-dining' as const, priceRange: 'expensive' as const, averageCost: 2500, rating: 4.7, mustTry: ['Dal Bukhara', 'Sikandari Raan', 'Naan'], coordinates: { lat: 27.1700, lng: 78.0350 }, openingTime: '12:30', closingTime: '23:00', vegetarian: false, description: 'Legendary North Indian restaurant at ITC Mughal, a sister of Delhi\'s iconic Bukhara.' },
  { _id: 'mama_chicken_agra', name: 'Mama Chicken', cityName: 'Agra', cuisine: ['Mughlai', 'Street Food'], type: 'street-food' as const, priceRange: 'budget' as const, averageCost: 150, rating: 4.3, mustTry: ['Chicken Shawarma', 'Biryani', 'Seekh Kebab'], coordinates: { lat: 27.1780, lng: 78.0200 }, openingTime: '11:00', closingTime: '23:00', vegetarian: false, description: 'Popular local joint for no-nonsense Mughlai street food near Sadar Bazaar.' },
  { _id: 'pinch_of_spice_agra', name: 'Pinch of Spice', cityName: 'Agra', cuisine: ['North Indian', 'Chinese', 'Continental'], type: 'casual' as const, priceRange: 'moderate' as const, averageCost: 600, rating: 4.4, mustTry: ['Paneer Tikka', 'Butter Chicken', 'Galouti Kebab'], coordinates: { lat: 27.1810, lng: 78.0180 }, openingTime: '11:00', closingTime: '23:00', vegetarian: false, description: 'Agra\'s go-to multi-cuisine restaurant with consistent quality and rooftop seating.' },
  // VARANASI
  { _id: 'kashi_chat_bhandar', name: 'Kashi Chat Bhandar', cityName: 'Varanasi', cuisine: ['Street Food', 'Chaat'], type: 'street-food' as const, priceRange: 'budget' as const, averageCost: 80, rating: 4.4, mustTry: ['Tamatar Chaat', 'Palak Chaat', 'Tikki'], coordinates: { lat: 25.3100, lng: 83.0100 }, openingTime: '10:00', closingTime: '22:00', vegetarian: true, description: 'Legendary chaat shop near Dashashwamedh Ghat — the tamatar chaat is a Varanasi institution.' },
  { _id: 'baati_chokha_varanasi', name: 'Baati Chokha', cityName: 'Varanasi', cuisine: ['North Indian', 'Bihari'], type: 'casual' as const, priceRange: 'moderate' as const, averageCost: 400, rating: 4.5, mustTry: ['Litti Chokha', 'Sattu Paratha', 'Lassi'], coordinates: { lat: 25.3000, lng: 83.0050 }, openingTime: '11:00', closingTime: '22:30', vegetarian: true, description: 'Rustic restaurant specializing in regional cuisine from Bihar and UP.' },
  { _id: 'brijwasi_varanasi', name: 'Brijwasi', cityName: 'Varanasi', cuisine: ['Sweets', 'North Indian'], type: 'casual' as const, priceRange: 'budget' as const, averageCost: 200, rating: 4.2, mustTry: ['Malaiyo', 'Rabri', 'Kachori'], coordinates: { lat: 25.3120, lng: 83.0090 }, openingTime: '07:00', closingTime: '22:00', vegetarian: true, description: 'Famous for seasonal Malaiyo (winter only) and traditional sweets near the ghats.' },
  // LUCKNOW
  { _id: 'tunday_kababi', name: 'Tunday Kababi', cityName: 'Lucknow', cuisine: ['Mughlai', 'Kebab'], type: 'street-food' as const, priceRange: 'budget' as const, averageCost: 150, rating: 4.6, mustTry: ['Galouti Kebab', 'Rumali Roti', 'Biryani'], coordinates: { lat: 26.8600, lng: 80.9100 }, openingTime: '10:00', closingTime: '23:00', vegetarian: false, description: 'Lucknow\'s most iconic kebab shop since 1905 — the galouti kebabs are transcendent.' },
  { _id: 'idris_biryani', name: 'Idris Biryani', cityName: 'Lucknow', cuisine: ['Mughlai', 'Biryani', 'Awadhi'], type: 'casual' as const, priceRange: 'moderate' as const, averageCost: 350, rating: 4.5, mustTry: ['Lucknowi Biryani', 'Nihari', 'Korma'], coordinates: { lat: 26.8650, lng: 80.9150 }, openingTime: '11:00', closingTime: '23:00', vegetarian: false, description: 'Popular biryani spot in Old Lucknow with authentic Awadhi flavors.' },
  { _id: 'oudhyana_lucknow', name: 'Oudhyana (Taj)', cityName: 'Lucknow', cuisine: ['Awadhi', 'Fine Dining'], type: 'fine-dining' as const, priceRange: 'expensive' as const, averageCost: 2500, rating: 4.7, mustTry: ['Raan-e-Lucknowi', 'Awadhi Thali', 'Sheermal'], coordinates: { lat: 26.8500, lng: 80.9500 }, openingTime: '12:30', closingTime: '23:00', vegetarian: false, description: 'Fine dining at Taj Lucknow celebrating royal Awadhi cuisine.' },
  // BHOPAL
  { _id: 'chappan_dukan', name: 'Chappan Dukan', cityName: 'Bhopal', cuisine: ['Street Food', 'Snacks'], type: 'street-food' as const, priceRange: 'budget' as const, averageCost: 100, rating: 4.3, mustTry: ['Poha Jalebi', 'Bhutte Ka Kees', 'Samosa'], coordinates: { lat: 23.2400, lng: 77.4100 }, openingTime: '08:00', closingTime: '22:00', vegetarian: true, description: '56 shops in a famous food lane — Bhopal\'s street food capital.' },
  { _id: 'manohar_dairy', name: 'Manohar Dairy & Restaurant', cityName: 'Bhopal', cuisine: ['North Indian', 'Sweets'], type: 'casual' as const, priceRange: 'moderate' as const, averageCost: 250, rating: 4.4, mustTry: ['Samosa', 'Khopra Patties', 'Thali'], coordinates: { lat: 23.2550, lng: 77.4050 }, openingTime: '08:00', closingTime: '22:30', vegetarian: true, description: 'Bhopal institution since 1957 — the samosas and khopra patties are legendary.' },
  { _id: 'jehan_numa_dining', name: 'Under The Mango Tree', cityName: 'Bhopal', cuisine: ['Continental', 'Indian'], type: 'fine-dining' as const, priceRange: 'expensive' as const, averageCost: 1800, rating: 4.6, mustTry: ['Grilled Lamb', 'Paneer Tikka', 'Wood-fired Pizza'], coordinates: { lat: 23.2400, lng: 77.4000 }, openingTime: '12:00', closingTime: '23:00', vegetarian: false, description: 'Al-fresco fine dining at Jehan Numa Palace under century-old mango trees.' },
  // KOCHI
  { _id: 'dal_roti_kochi', name: 'Dal Roti', cityName: 'Kochi', cuisine: ['North Indian', 'Punjabi'], type: 'casual' as const, priceRange: 'moderate' as const, averageCost: 350, rating: 4.5, mustTry: ['Dal Makhani', 'Butter Naan', 'Paneer'], coordinates: { lat: 9.9640, lng: 76.2420 }, openingTime: '11:00', closingTime: '22:30', vegetarian: false, description: 'Tucked in Fort Kochi lanes, this tiny gem serves soulful North Indian food.' },
  { _id: 'kayees_kochi', name: 'Kayees Biryani', cityName: 'Kochi', cuisine: ['Kerala', 'Biryani'], type: 'casual' as const, priceRange: 'budget' as const, averageCost: 200, rating: 4.4, mustTry: ['Malabar Biryani', 'Fish Fry', 'Pathiri'], coordinates: { lat: 9.9700, lng: 76.2850 }, openingTime: '11:30', closingTime: '22:00', vegetarian: false, description: 'Kochi\'s oldest biryani joint — fragrant Malabar biryani since 1948.' },
  { _id: 'old_harbour_dining', name: 'Malabar Junction', cityName: 'Kochi', cuisine: ['Kerala', 'Continental', 'Seafood'], type: 'fine-dining' as const, priceRange: 'expensive' as const, averageCost: 1500, rating: 4.6, mustTry: ['Karimeen Pollichathu', 'Kerala Prawn Curry', 'Appam'], coordinates: { lat: 9.9645, lng: 76.2435 }, openingTime: '12:00', closingTime: '22:30', vegetarian: false, description: 'Elegant restaurant at Malabar House with creative Kerala-European fusion.' }
];

