// This file provides curated data for the MVP (Rajasthan)
// It mimics the database queries for the sandbox environment where MongoDB is not available.

export const STATES = [
  {
    _id: 'RJ',
    code: 'RJ',
    name: 'Rajasthan',
    center: { lat: 26.5, lng: 73.8 },
    zoom: 7,
    description: 'The Land of Kings, featuring forts, deserts, and vibrant culture.',
    imageUrl: 'https://images.unsplash.com/photo-1477587458883-47145ed94245?auto=format&fit=crop&q=80',
  },
  {
    _id: 'KL',
    code: 'KL',
    name: 'Kerala',
    center: { lat: 10.8505, lng: 76.2711 },
    zoom: 7,
    description: "God's Own Country, known for its backwaters, beaches, and tea gardens.",
    imageUrl: 'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?auto=format&fit=crop&q=80',
  },
  {
    _id: 'GA',
    code: 'GA',
    name: 'Goa',
    center: { lat: 15.2993, lng: 74.1240 },
    zoom: 9,
    description: 'Famous for its beaches, Portuguese heritage, and vibrant nightlife.',
    imageUrl: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&q=80',
  },
  {
    _id: 'HP',
    code: 'HP',
    name: 'Himachal Pradesh',
    center: { lat: 31.1048, lng: 77.1734 },
    zoom: 7,
    description: 'A mountain lover’s paradise with snow-capped peaks and scenic valleys.',
    imageUrl: 'https://images.unsplash.com/photo-1562939884-257859b31d8e?auto=format&fit=crop&q=80',
  }
];

export const PACKAGES = [
  {
    id: 'royal-rajasthan',
    title: 'Royal Rajasthan Heritage',
    state: 'Rajasthan',
    days: 7,
    price: 35000,
    image: 'https://images.unsplash.com/photo-1477587458883-47145ed94245?auto=format&fit=crop&q=80',
    description: 'Experience the grandeur of forts and palaces in Jaipur, Jodhpur, and Udaipur.',
    tags: ['Heritage', 'Luxury', 'Culture']
  },
  {
    id: 'kerala-backwaters',
    title: 'Kerala Backwaters & Hills',
    state: 'Kerala',
    days: 5,
    price: 25000,
    image: 'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?auto=format&fit=crop&q=80',
    description: 'Relax on houseboats in Alleppey and explore the tea gardens of Munnar.',
    tags: ['Nature', 'Relaxation', 'Honeymoon']
  },
  {
    id: 'goa-beach-party',
    title: 'Goa Sun & Sand',
    state: 'Goa',
    days: 4,
    price: 15000,
    image: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&q=80',
    description: 'Enjoy the best beaches, water sports, and nightlife in North Goa.',
    tags: ['Beaches', 'Nightlife', 'Friends']
  }
];

export const CITIES = [
  // RAJASTHAN
  {
    _id: 'jaipur',
    name: 'Jaipur',
    stateCode: 'RAJASTHAN',
    coordinates: { lat: 26.9124, lng: 75.7873 },
    tier: 'tier1',
    description: 'The Pink City, famous for Hawa Mahal, Amer Fort, and City Palace.',
    idealDays: 2,
    imageUrl: 'https://images.unsplash.com/photo-1477587458883-47145ed94245?auto=format&fit=crop&q=80',
  },
  {
    _id: 'udaipur',
    name: 'Udaipur',
    stateCode: 'RAJASTHAN',
    coordinates: { lat: 24.5854, lng: 73.7125 },
    tier: 'tier1',
    description: 'The City of Lakes, known for its romantic setting and palaces.',
    idealDays: 2,
    imageUrl: 'https://images.unsplash.com/photo-1615836245337-f5b9b2303f10?auto=format&fit=crop&q=80',
  },
  {
    _id: 'jodhpur',
    name: 'Jodhpur',
    stateCode: 'RAJASTHAN',
    coordinates: { lat: 26.2389, lng: 73.0243 },
    tier: 'tier2',
    description: 'The Blue City, dominated by the massive Mehrangarh Fort.',
    idealDays: 2,
    imageUrl: 'https://images.unsplash.com/photo-1590449911964-b04b6b64731c?auto=format&fit=crop&q=80',
  },
  {
    _id: 'jaisalmer',
    name: 'Jaisalmer',
    stateCode: 'RAJASTHAN',
    coordinates: { lat: 26.9157, lng: 70.9083 },
    tier: 'tier2',
    description: 'The Golden City, located in the heart of the Thar Desert.',
    idealDays: 2,
    imageUrl: 'https://images.unsplash.com/photo-1516483638261-f4dbaf036963?auto=format&fit=crop&q=80',
  },
  // KERALA (Mock)
  {
    _id: 'munnar',
    name: 'Munnar',
    stateCode: 'KERALA',
    coordinates: { lat: 10.0889, lng: 77.0595 },
    tier: 'tier2',
    description: 'A hill station famous for its tea estates and misty mountains.',
    idealDays: 2,
    imageUrl: 'https://images.unsplash.com/photo-1596323674681-424d86b856b3?auto=format&fit=crop&q=80',
  },
  {
    _id: 'alleppey',
    name: 'Alleppey',
    stateCode: 'KERALA',
    coordinates: { lat: 9.4981, lng: 76.3388 },
    tier: 'tier2',
    description: 'Known as the Venice of the East, famous for houseboat cruises.',
    idealDays: 1,
    imageUrl: 'https://images.unsplash.com/photo-1593693397690-362cb9666fc2?auto=format&fit=crop&q=80',
  },
  // GOA
  {
    _id: 'north_goa',
    name: 'North Goa',
    stateCode: 'GOA',
    coordinates: { lat: 15.5449, lng: 73.7551 },
    tier: 'tier1',
    description: 'Famous for beaches, nightlife, and water sports.',
    idealDays: 2,
    imageUrl: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&q=80',
  },
  {
    _id: 'old_goa',
    name: 'Old Goa',
    stateCode: 'GOA',
    coordinates: { lat: 15.5009, lng: 73.9116 },
    tier: 'tier2',
    description: 'Historic capital with UNESCO World Heritage churches.',
    idealDays: 1,
    imageUrl: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&q=80',
  },
  // MAHARASHTRA
  {
    _id: 'mumbai',
    name: 'Mumbai',
    stateCode: 'MAHARASHTR',
    coordinates: { lat: 18.9220, lng: 72.8347 },
    tier: 'tier1',
    description: 'The City of Dreams, financial capital of India.',
    idealDays: 3,
    imageUrl: 'https://images.unsplash.com/photo-1570168007204-dfb528c6958f?auto=format&fit=crop&q=80',
  },
  {
    _id: 'aurangabad',
    name: 'Aurangabad',
    stateCode: 'MAHARASHTR',
    coordinates: { lat: 19.8762, lng: 75.3433 },
    tier: 'tier2',
    description: 'Gateway to Ajanta and Ellora caves.',
    idealDays: 2,
    imageUrl: 'https://images.unsplash.com/photo-1570168007204-dfb528c6958f?auto=format&fit=crop&q=80',
  },
  // TAMIL NADU
  {
    _id: 'chennai',
    name: 'Chennai',
    stateCode: 'TAMIL_NADU',
    coordinates: { lat: 13.0827, lng: 80.2707 },
    tier: 'tier1',
    description: 'Cultural capital of South India with rich heritage.',
    idealDays: 2,
    imageUrl: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&q=80',
  },
  {
    _id: 'madurai',
    name: 'Madurai',
    stateCode: 'TAMIL_NADU',
    coordinates: { lat: 9.9252, lng: 78.1198 },
    tier: 'tier2',
    description: 'One of the oldest cities, famous for Meenakshi Temple.',
    idealDays: 2,
    imageUrl: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&q=80',
  },
  // WEST BENGAL
  {
    _id: 'kolkata',
    name: 'Kolkata',
    stateCode: 'WEST_BENGA',
    coordinates: { lat: 22.5726, lng: 88.3639 },
    tier: 'tier1',
    description: 'City of Joy, known for its colonial heritage and culture.',
    idealDays: 3,
    imageUrl: 'https://images.unsplash.com/photo-1558431382-27e303142255?auto=format&fit=crop&q=80',
  },
  // KARNATAKA
  {
    _id: 'mysore',
    name: 'Mysore',
    stateCode: 'KARNATAKA',
    coordinates: { lat: 12.2958, lng: 76.6394 },
    tier: 'tier2',
    description: 'City of Palaces, known for its royal heritage.',
    idealDays: 2,
    imageUrl: 'https://images.unsplash.com/photo-1600100397608-6c5f54b32ea7?auto=format&fit=crop&q=80',
  },
  {
    _id: 'hampi_city',
    name: 'Hampi',
    stateCode: 'KARNATAKA',
    coordinates: { lat: 15.3350, lng: 76.4600 },
    tier: 'tier2',
    description: 'UNESCO World Heritage Site with ancient Vijayanagara ruins.',
    idealDays: 2,
    imageUrl: 'https://images.unsplash.com/photo-1600100397608-6c5f54b32ea7?auto=format&fit=crop&q=80',
  },
  // GUJARAT
  {
    _id: 'kutch',
    name: 'Kutch',
    stateCode: 'GUJARAT',
    coordinates: { lat: 23.7337, lng: 69.8597 },
    tier: 'tier2',
    description: 'Famous for the white salt desert Rann of Kutch.',
    idealDays: 2,
    imageUrl: 'https://images.unsplash.com/photo-1589308078059-be1415eab4c3?auto=format&fit=crop&q=80',
  },
  {
    _id: 'kevadia',
    name: 'Kevadia',
    stateCode: 'GUJARAT',
    coordinates: { lat: 21.8380, lng: 73.7191 },
    tier: 'tier2',
    description: 'Home to the Statue of Unity, the world\'s tallest statue.',
    idealDays: 1,
    imageUrl: 'https://images.unsplash.com/photo-1589308078059-be1415eab4c3?auto=format&fit=crop&q=80',
  }
];

export const PLACES = [
  // JAIPUR
  {
    _id: 'amber_fort',
    name: 'Amber Fort',
    cityName: 'Jaipur',
    type: 'Fort',
    coordinates: { lat: 26.9855, lng: 75.8513 },
    timeRequired: 3,
    openingTime: '08:00',
    closingTime: '17:30',
    bestTimeOfDay: 'morning',
    rating: 4.8,
    tags: ['history', 'photography'],
    priceTier: 'medium',
  },
  {
    _id: 'hawa_mahal',
    name: 'Hawa Mahal',
    cityName: 'Jaipur',
    type: 'Palace',
    coordinates: { lat: 26.9239, lng: 75.8267 },
    timeRequired: 1,
    openingTime: '09:00',
    closingTime: '16:30',
    bestTimeOfDay: 'morning',
    rating: 4.5,
    tags: ['history', 'architecture'],
    priceTier: 'low',
  },
  {
    _id: 'city_palace_jaipur',
    name: 'City Palace',
    cityName: 'Jaipur',
    type: 'Palace',
    coordinates: { lat: 26.9258, lng: 75.8237 },
    timeRequired: 2,
    openingTime: '09:30',
    closingTime: '17:00',
    bestTimeOfDay: 'afternoon',
    rating: 4.6,
    tags: ['history', 'museum', 'senior-friendly'],
    priceTier: 'high',
  },
  {
    _id: 'jantar_mantar',
    name: 'Jantar Mantar',
    cityName: 'Jaipur',
    type: 'Observatory',
    coordinates: { lat: 26.9248, lng: 75.8246 },
    timeRequired: 1,
    openingTime: '09:00',
    closingTime: '16:30',
    bestTimeOfDay: 'any',
    rating: 4.4,
    tags: ['science', 'history', 'senior-friendly'],
    priceTier: 'low',
  },
  {
    _id: 'nahargarh_fort',
    name: 'Nahargarh Fort',
    cityName: 'Jaipur',
    type: 'Fort',
    coordinates: { lat: 26.9386, lng: 75.8163 },
    timeRequired: 2,
    openingTime: '10:00',
    closingTime: '22:00',
    bestTimeOfDay: 'evening',
    rating: 4.5,
    tags: ['views', 'sunset'],
    priceTier: 'medium',
  },

  // UDAIPUR
  {
    _id: 'city_palace_udaipur',
    name: 'City Palace',
    cityName: 'Udaipur',
    type: 'Palace',
    coordinates: { lat: 24.5764, lng: 73.6835 },
    timeRequired: 3,
    openingTime: '09:30',
    closingTime: '17:30',
    bestTimeOfDay: 'morning',
    rating: 4.7,
    tags: ['history', 'lake_view'],
    priceTier: 'high',
  },
  {
    _id: 'lake_pichola',
    name: 'Lake Pichola',
    cityName: 'Udaipur',
    type: 'Lake',
    coordinates: { lat: 24.5726, lng: 73.6744 },
    timeRequired: 2,
    openingTime: '00:00',
    closingTime: '23:59',
    bestTimeOfDay: 'evening',
    rating: 4.8,
    tags: ['nature', 'romantic', 'boating'],
    priceTier: 'medium',
  },
  {
    _id: 'saheliyon_ki_bari',
    name: 'Saheliyon Ki Bari',
    cityName: 'Udaipur',
    type: 'Garden',
    coordinates: { lat: 24.6033, lng: 73.6881 },
    timeRequired: 1,
    openingTime: '09:00',
    closingTime: '19:00',
    bestTimeOfDay: 'morning',
    rating: 4.3,
    tags: ['nature', 'senior-friendly', 'relaxed'],
    priceTier: 'low',
  },
  {
    _id: 'jagdish_temple',
    name: 'Jagdish Temple',
    cityName: 'Udaipur',
    type: 'Temple',
    coordinates: { lat: 24.5796, lng: 73.6844 },
    timeRequired: 0.5,
    openingTime: '05:00',
    closingTime: '21:00',
    bestTimeOfDay: 'morning',
    rating: 4.6,
    tags: ['religious', 'senior-friendly'],
    priceTier: 'free',
  },

  // JODHPUR
  {
    _id: 'mehrangarh_fort',
    name: 'Mehrangarh Fort',
    cityName: 'Jodhpur',
    type: 'Fort',
    coordinates: { lat: 26.2975, lng: 73.0185 },
    timeRequired: 3,
    openingTime: '09:00',
    closingTime: '17:00',
    bestTimeOfDay: 'morning',
    rating: 4.9,
    tags: ['history', 'views', 'must-visit'],
    priceTier: 'medium',
  },
  {
    _id: 'jaswant_thada',
    name: 'Jaswant Thada',
    cityName: 'Jodhpur',
    type: 'Monument',
    coordinates: { lat: 26.3040, lng: 73.0238 },
    timeRequired: 1,
    openingTime: '09:00',
    closingTime: '17:00',
    bestTimeOfDay: 'morning',
    rating: 4.5,
    tags: ['history', 'peaceful'],
    priceTier: 'low',
  },
  {
    _id: 'umaid_bhawan',
    name: 'Umaid Bhawan Palace',
    cityName: 'Jodhpur',
    type: 'Palace',
    coordinates: { lat: 26.2808, lng: 73.0474 },
    timeRequired: 2,
    openingTime: '10:00',
    closingTime: '16:30',
    bestTimeOfDay: 'any',
    rating: 4.6,
    tags: ['luxury', 'museum', 'history'],
    priceTier: 'high',
  },

  // JAISALMER
  {
    _id: 'jaisalmer_fort',
    name: 'Jaisalmer Fort',
    cityName: 'Jaisalmer',
    type: 'Fort',
    coordinates: { lat: 26.9124, lng: 70.9127 },
    timeRequired: 3,
    openingTime: '00:00',
    closingTime: '23:59', // Living fort
    bestTimeOfDay: 'morning',
    rating: 4.7,
    tags: ['history', 'walking', 'living_fort'],
    priceTier: 'free',
  },
  {
    _id: 'patwon_ki_haveli',
    name: 'Patwon Ki Haveli',
    cityName: 'Jaisalmer',
    type: 'Haveli',
    coordinates: { lat: 26.9152, lng: 70.9137 },
    timeRequired: 1.5,
    openingTime: '09:00',
    closingTime: '18:00',
    bestTimeOfDay: 'afternoon',
    rating: 4.5,
    tags: ['architecture', 'history'],
    priceTier: 'medium',
  },
  {
    _id: 'sam_sand_dunes',
    name: 'Sam Sand Dunes',
    cityName: 'Jaisalmer',
    type: 'Desert',
    coordinates: { lat: 26.8375, lng: 70.5283 },
    timeRequired: 4,
    openingTime: '00:00',
    closingTime: '23:59',
    bestTimeOfDay: 'evening',
    rating: 4.6,
    tags: ['nature', 'adventure', 'camel_ride', 'sunset'],
    priceTier: 'medium',
  },

  // KERALA PLACES (Mock)
  {
    _id: 'tea_museum',
    name: 'Tea Museum',
    cityName: 'Munnar',
    type: 'Museum',
    coordinates: { lat: 10.0889, lng: 77.0595 },
    timeRequired: 1,
    openingTime: '09:00',
    closingTime: '17:00',
    bestTimeOfDay: 'morning',
    rating: 4.4,
    tags: ['history', 'nature'],
    priceTier: 'low',
  },
  {
    _id: 'alleppey_backwaters',
    name: 'Alleppey Backwaters',
    cityName: 'Alleppey',
    type: 'Lake',
    coordinates: { lat: 9.4981, lng: 76.3388 },
    timeRequired: 4,
    openingTime: '00:00',
    closingTime: '23:59',
    bestTimeOfDay: 'evening',
    rating: 4.8,
    tags: ['nature', 'romantic'],
    priceTier: 'medium',
  },

  // GOA PLACES
  {
    _id: 'calangute_beach',
    name: 'Calangute Beach',
    cityName: 'North Goa',
    type: 'Beach',
    coordinates: { lat: 15.5449, lng: 73.7551 },
    timeRequired: 3,
    openingTime: '00:00',
    closingTime: '23:59',
    bestTimeOfDay: 'evening',
    rating: 4.3,
    tags: ['beach', 'water_sports', 'nightlife'],
    priceTier: 'low',
  },
  {
    _id: 'basilica_bom_jesus',
    name: 'Basilica of Bom Jesus',
    cityName: 'Old Goa',
    type: 'Church',
    coordinates: { lat: 15.5009, lng: 73.9116 },
    timeRequired: 1,
    openingTime: '09:00',
    closingTime: '18:30',
    bestTimeOfDay: 'morning',
    rating: 4.6,
    tags: ['heritage', 'religious', 'UNESCO'],
    priceTier: 'free',
  },

  // MAHARASHTRA PLACES
  {
    _id: 'gateway_of_india',
    name: 'Gateway of India',
    cityName: 'Mumbai',
    type: 'Monument',
    coordinates: { lat: 18.9220, lng: 72.8347 },
    timeRequired: 1,
    openingTime: '00:00',
    closingTime: '23:59',
    bestTimeOfDay: 'evening',
    rating: 4.5,
    tags: ['heritage', 'landmark'],
    priceTier: 'free',
  },
  {
    _id: 'ajanta_caves',
    name: 'Ajanta Caves',
    cityName: 'Aurangabad',
    type: 'Cave',
    coordinates: { lat: 20.5519, lng: 75.7033 },
    timeRequired: 4,
    openingTime: '09:00',
    closingTime: '17:00',
    bestTimeOfDay: 'morning',
    rating: 4.7,
    tags: ['heritage', 'UNESCO', 'history'],
    priceTier: 'medium',
  },

  // TAMIL NADU PLACES
  {
    _id: 'meenakshi_temple',
    name: 'Meenakshi Amman Temple',
    cityName: 'Madurai',
    type: 'Temple',
    coordinates: { lat: 9.9195, lng: 78.1193 },
    timeRequired: 2,
    openingTime: '05:00',
    closingTime: '21:00',
    bestTimeOfDay: 'morning',
    rating: 4.8,
    tags: ['religious', 'heritage', 'architecture'],
    priceTier: 'free',
  },
  {
    _id: 'marina_beach',
    name: 'Marina Beach',
    cityName: 'Chennai',
    type: 'Beach',
    coordinates: { lat: 13.0500, lng: 80.2824 },
    timeRequired: 2,
    openingTime: '00:00',
    closingTime: '23:59',
    bestTimeOfDay: 'evening',
    rating: 4.4,
    tags: ['beach', 'relaxation'],
    priceTier: 'free',
  },

  // WEST BENGAL PLACES
  {
    _id: 'victoria_memorial',
    name: 'Victoria Memorial',
    cityName: 'Kolkata',
    type: 'Monument',
    coordinates: { lat: 22.5448, lng: 88.3426 },
    timeRequired: 2,
    openingTime: '10:00',
    closingTime: '18:00',
    bestTimeOfDay: 'afternoon',
    rating: 4.7,
    tags: ['heritage', 'museum', 'gardens'],
    priceTier: 'medium',
  },
  {
    _id: 'howrah_bridge',
    name: 'Howrah Bridge',
    cityName: 'Kolkata',
    type: 'Landmark',
    coordinates: { lat: 22.5851, lng: 88.3468 },
    timeRequired: 1,
    openingTime: '00:00',
    closingTime: '23:59',
    bestTimeOfDay: 'evening',
    rating: 4.5,
    tags: ['landmark', 'iconic'],
    priceTier: 'free',
  },

  // KARNATAKA PLACES
  {
    _id: 'mysore_palace',
    name: 'Mysore Palace',
    cityName: 'Mysore',
    type: 'Palace',
    coordinates: { lat: 12.3052, lng: 76.6552 },
    timeRequired: 2,
    openingTime: '10:00',
    closingTime: '17:30',
    bestTimeOfDay: 'morning',
    rating: 4.7,
    tags: ['heritage', 'architecture', 'royal'],
    priceTier: 'medium',
  },
  {
    _id: 'hampi',
    name: 'Hampi Ruins',
    cityName: 'Hampi',
    type: 'Heritage',
    coordinates: { lat: 15.3350, lng: 76.4600 },
    timeRequired: 6,
    openingTime: '06:00',
    closingTime: '18:00',
    bestTimeOfDay: 'morning',
    rating: 4.8,
    tags: ['heritage', 'UNESCO', 'history'],
    priceTier: 'low',
  },

  // GUJARAT PLACES
  {
    _id: 'statue_of_unity',
    name: 'Statue of Unity',
    cityName: 'Kevadia',
    type: 'Monument',
    coordinates: { lat: 21.8380, lng: 73.7191 },
    timeRequired: 3,
    openingTime: '08:00',
    closingTime: '18:00',
    bestTimeOfDay: 'morning',
    rating: 4.6,
    tags: ['landmark', 'modern', 'views'],
    priceTier: 'medium',
  },
  {
    _id: 'rann_of_kutch',
    name: 'Rann of Kutch',
    cityName: 'Kutch',
    type: 'Desert',
    coordinates: { lat: 23.7337, lng: 69.8597 },
    timeRequired: 4,
    openingTime: '00:00',
    closingTime: '23:59',
    bestTimeOfDay: 'evening',
    rating: 4.7,
    tags: ['nature', 'desert', 'unique'],
    priceTier: 'medium',
  }
];
