import { FC } from 'react';
import { Link } from 'react-router-dom';


const services = [
    {
        icon: (
            <svg className="w-7 h-7 text-blue-600" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M9 20l-5.447-2.724A1 1 0 013 16.382V5.618a1 1 0 011.447-.894L9 7m0 13l6-3m-6 3V7m6 10l5.447 2.724A1 1 0 0021 18.382V7.618a1 1 0 00-.553-.894L15 4m0 13V4m0 0L9 7" />
            </svg>
        ),
        title: 'AI-Powered Itineraries',
        description: 'Get optimized day-wise travel plans generated by our smart algorithm. It considers travel distances, opening hours, and your personal pace to build the perfect schedule.',
        color: 'blue',
    },
    {
        icon: (
            <svg className="w-7 h-7 text-amber-600" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M17 9V7a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2m2 4h10a2 2 0 002-2v-6a2 2 0 00-2-2H9a2 2 0 00-2 2v6a2 2 0 002 2zm7-5a2 2 0 11-4 0 2 2 0 014 0z" />
            </svg>
        ),
        title: 'Budget Estimation',
        description: 'Know your trip costs before you go. We provide detailed budget breakdowns including hotel stays, transportation, entry fees, and food estimates across three budget tiers.',
        color: 'amber',
    },
    {
        icon: (
            <svg className="w-7 h-7 text-green-600" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M17 20h5v-2a3 3 0 00-5.356-1.857M17 20H7m10 0v-2c0-.656-.126-1.283-.356-1.857M7 20H2v-2a3 3 0 015.356-1.857M7 20v-2c0-.656.126-1.283.356-1.857m0 0a5.002 5.002 0 019.288 0M15 7a3 3 0 11-6 0 3 3 0 016 0zm6 3a2 2 0 11-4 0 2 2 0 014 0zM7 10a2 2 0 11-4 0 2 2 0 014 0z" />
            </svg>
        ),
        title: 'Group Trip Planning',
        description: 'Plan trips together with friends and family. Create groups, share itineraries, vote on changes, and coordinate using built-in chat and polls.',
        color: 'green',
    },
    {
        icon: (
            <svg className="w-7 h-7 text-purple-600" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M19 21V5a2 2 0 00-2-2H7a2 2 0 00-2 2v16m14 0h2m-2 0h-5m-9 0H3m2 0h5M9 7h1m-1 4h1m4-4h1m-1 4h1m-5 10v-5a1 1 0 011-1h2a1 1 0 011 1v5m-4 0h4" />
            </svg>
        ),
        title: 'Hotel & Restaurant Finder',
        description: 'Discover hotels across budget, mid-range, and luxury tiers in every city. Browse restaurants filtered by cuisine, veg/non-veg, and ratings.',
        color: 'purple',
    },
    {
        icon: (
            <svg className="w-7 h-7 text-rose-600" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M3.055 11H5a2 2 0 012 2v1a2 2 0 002 2 2 2 0 012 2v2.945M8 3.935V5.5A2.5 2.5 0 0010.5 8h.5a2 2 0 012 2 2 2 0 104 0 2 2 0 012-2h1.064M15 20.488V18a2 2 0 012-2h3.064M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
            </svg>
        ),
        title: 'Interactive Maps',
        description: 'Visualize your entire trip on interactive maps. See routes between cities, locate attractions, and understand travel distances at a glance.',
        color: 'rose',
    },
    {
        icon: (
            <svg className="w-7 h-7 text-cyan-600" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z" />
            </svg>
        ),
        title: 'Train & Transport Info',
        description: 'Access real-time train schedules, PNR status, seat availability, and fare information. Get optimal transport recommendations between cities.',
        color: 'cyan',
    },
    {
        icon: (
            <svg className="w-7 h-7 text-orange-600" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M3 15a4 4 0 004 4h9a5 5 0 10-.1-9.999 5.002 5.002 0 10-9.78 2.096A4.001 4.001 0 003 15z" />
            </svg>
        ),
        title: 'Weather Forecasts',
        description: 'Check current and seasonal weather conditions for any destination. Get packing advice and best time to visit recommendations.',
        color: 'orange',
    },
    {
        icon: (
            <svg className="w-7 h-7 text-indigo-600" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M11.049 2.927c.3-.921 1.603-.921 1.902 0l1.519 4.674a1 1 0 00.95.69h4.915c.969 0 1.371 1.24.588 1.81l-3.976 2.888a1 1 0 00-.363 1.118l1.518 4.674c.3.922-.755 1.688-1.538 1.118l-3.976-2.888a1 1 0 00-1.176 0l-3.976 2.888c-.783.57-1.838-.197-1.538-1.118l1.518-4.674a1 1 0 00-.363-1.118l-3.976-2.888c-.784-.57-.38-1.81.588-1.81h4.914a1 1 0 00.951-.69l1.519-4.674z" />
            </svg>
        ),
        title: 'Reviews & Journals',
        description: 'Rate and review places you\'ve visited. Keep a travel journal with photos, moods, and memories— share with the community or keep private.',
        color: 'indigo',
    },
];

const bgMap: Record<string, string> = {
    blue: 'bg-blue-50 dark:bg-blue-900/20',
    amber: 'bg-amber-50 dark:bg-amber-900/20',
    green: 'bg-green-50 dark:bg-green-900/20',
    purple: 'bg-purple-50 dark:bg-purple-900/20',
    rose: 'bg-rose-50 dark:bg-rose-900/20',
    cyan: 'bg-cyan-50 dark:bg-cyan-900/20',
    orange: 'bg-orange-50 dark:bg-orange-900/20',
    indigo: 'bg-indigo-50 dark:bg-indigo-900/20',
};

export const Services: FC = () => {
    return (
        <div className="min-h-screen bg-white dark:bg-slate-950">
            {/* Hero */}
            <section className="relative overflow-hidden bg-gradient-to-br from-blue-50 via-white to-amber-50 dark:from-slate-900 dark:via-slate-950 dark:to-slate-900 py-12 sm:py-20 px-4 sm:px-6">
                <div className="max-w-4xl mx-auto text-center">
                    <h1 className="text-3xl sm:text-4xl md:text-5xl font-bold text-slate-900 dark:text-white mb-4">
                        Our <span className="text-blue-600">Services</span>
                    </h1>
                    <p className="text-lg text-slate-600 dark:text-slate-400 max-w-2xl mx-auto">
                        Everything you need to plan, book, and enjoy your trip across India — all in one platform.
                    </p>
                </div>
            </section>

            {/* Services Grid */}
            <section className="py-10 sm:py-16 px-4 sm:px-6">
                <div className="max-w-6xl mx-auto grid sm:grid-cols-2 lg:grid-cols-4 gap-5">
                    {services.map((service) => (
                        <div
                            key={service.title}
                            className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-2xl p-6 hover:shadow-lg transition-shadow"
                        >
                            <div className={`w-14 h-14 ${bgMap[service.color]} rounded-xl flex items-center justify-center mb-4`}>
                                {service.icon}
                            </div>
                            <h3 className="text-base font-semibold text-slate-900 dark:text-white mb-2">{service.title}</h3>
                            <p className="text-sm text-slate-600 dark:text-slate-400 leading-relaxed">{service.description}</p>
                        </div>
                    ))}
                </div>
            </section>

            {/* CTA */}
            <section className="py-10 sm:py-14 px-4 sm:px-6 bg-slate-50 dark:bg-slate-900">
                <div className="max-w-3xl mx-auto text-center">
                    <h2 className="text-2xl font-bold text-slate-900 dark:text-white mb-3">Ready to experience it?</h2>
                    <p className="text-slate-600 dark:text-slate-400 mb-6">
                        Start planning your trip today — it only takes a minute.
                    </p>
                    <div className="flex flex-wrap justify-center gap-3">
                        <Link to="/plan" className="bg-blue-600 text-white px-8 py-3 rounded-xl text-sm font-semibold hover:bg-blue-700 transition-colors">
                            Plan a Trip
                        </Link>
                        <Link to="/explore" className="bg-white dark:bg-slate-800 text-slate-700 dark:text-slate-200 border border-slate-200 dark:border-slate-700 px-8 py-3 rounded-xl text-sm font-semibold hover:bg-slate-50 dark:hover:bg-slate-700 transition-colors">
                            Explore Destinations
                        </Link>
                    </div>
                </div>
            </section>

        </div>
    );
};
